import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { Alert } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { usePermissions } from '@/hooks/usePermissions';
import { apiErrorMessage } from '@/lib/apiClient';
import { inventoryApi } from '../api/inventoryApi';
import { AssetForm } from '../components/AssetForm';
import { AssetTable } from '../components/AssetTable';
import { InventoryModal } from '../components/InventoryModal';
import type { AssetSchemaValues } from '../schemas';
import type { Asset, AssetFormValues } from '../types';

export const AssetsPage=()=>{const [sp,setSp]=useSearchParams();const [editing,setEditing]=useState<Asset|null|undefined>();const client=useQueryClient();const {can}=usePermissions();const page=Math.max(1,Number(sp.get('page')||1));const filters={page,per_page:20,search:sp.get('search')||undefined,status:sp.get('status')||undefined,assignment_type:sp.get('assignment_type')||undefined,warranty:sp.get('warranty')||undefined,sort:sp.get('sort')||'-created_at'};
const assets=useQuery({queryKey:['inventory','assets',filters],queryFn:()=>inventoryApi.assets(filters)});const products=useQuery({queryKey:['inventory','products','asset-form'],queryFn:()=>inventoryApi.products({per_page:100,status:'active'})});const vendors=useQuery({queryKey:['inventory','vendors'],queryFn:()=>inventoryApi.catalog('vendors')});const locations=useQuery({queryKey:['inventory','lookup','locations'],queryFn:()=>inventoryApi.lookup('warehouse-locations')});
const save=useMutation({mutationFn:(values:AssetSchemaValues)=>{const {warehouse_location_id,...base}=values;const payload={...base,...(!editing&&warehouse_location_id?{initial_assignment:{assignment_type:'warehouse' as const,warehouse_location_id}}:{})} as AssetFormValues;return editing?inventoryApi.updateAsset(editing.id,payload):inventoryApi.createAsset(payload);},onSuccess:()=>{setEditing(undefined);void client.invalidateQueries({queryKey:['inventory']});}});const remove=useMutation({mutationFn:inventoryApi.deleteAsset,onSuccess:()=>void client.invalidateQueries({queryKey:['inventory']})});const set=(key:string,value:string)=>{const next=new URLSearchParams(sp);if(value)next.set(key,value);else next.delete(key);if(key!=='page')next.delete('page');setSp(next,{replace:true});};const items=assets.data?.data.map(x=>x.attributes)??[];
return <div className="space-y-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold text-slate-900">Serialized Assets</h1><p className="mt-1 text-sm text-slate-500">Track serials, MAC addresses, warranty, custody, and deployment history.</p></div>{can('inventory.create')&&<Button onClick={()=>setEditing(null)}>Register asset</Button>}</header><div className="flex flex-wrap gap-3 rounded-xl border bg-white p-4"><input className="h-10 min-w-64 rounded-md border px-3 text-sm" placeholder="Asset tag, serial, MAC, barcode" value={sp.get('search')||''} onChange={e=>set('search',e.target.value)}/><select className="h-10 rounded-md border bg-white px-3 text-sm" value={sp.get('status')||''} onChange={e=>set('status',e.target.value)}><option value="">All statuses</option>{['in_stock','reserved','in_transit','assigned','deployed','under_repair','returned','damaged','lost','scrapped','retired'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select><select className="h-10 rounded-md border bg-white px-3 text-sm" value={sp.get('warranty')||''} onChange={e=>set('warranty',e.target.value)}><option value="">Any warranty</option><option value="active">Active</option><option value="expiring">Expiring in 30 days</option><option value="expired">Expired</option></select></div>{(assets.error||save.error||remove.error)&&<Alert title="Asset operation failed">{apiErrorMessage(assets.error||save.error||remove.error)}</Alert>}<AssetTable assets={items} isLoading={assets.isLoading} onEdit={can('inventory.update')?setEditing:undefined} onDelete={can('inventory.delete')?(asset)=>{if(confirm(`Retire ${asset.asset_tag}?`))remove.mutate(asset.id);}:undefined}/>{assets.data&&<div className="flex items-center justify-between rounded-xl border bg-white p-3 text-sm"><span className="text-slate-500">{assets.data.meta.total} assets</span><div className="flex gap-2"><Button size="sm" variant="secondary" disabled={page<=1} onClick={()=>set('page',String(page-1))}>Previous</Button><Button size="sm" variant="secondary" disabled={page>=assets.data.meta.last_page} onClick={()=>set('page',String(page+1))}>Next</Button></div></div>}{editing!==undefined&&<InventoryModal title={editing?'Edit asset':'Register asset'} onClose={()=>setEditing(undefined)} wide><AssetForm asset={editing} products={products.data?.data.map(x=>x.attributes)??[]} vendors={vendors.data??[]} locations={locations.data??[]} onSubmit={values=>save.mutate(values)} onCancel={()=>setEditing(undefined)} isLoading={save.isPending}/></InventoryModal>}</div>;
};
