import { Link } from 'react-router-dom';
import { Alert } from '@/components/ui/alert';
import { apiErrorMessage } from '@/lib/apiClient';
import { useInventoryDashboard } from '../api/useInventory';
import { InventoryStatistics } from '../components/InventoryStatistics';
import { InventoryStatusBadge } from '../components/InventoryStatusBadge';

export const InventoryDashboardPage = () => {
  const dashboard = useInventoryDashboard();
  if (dashboard.isLoading) return <div className="space-y-5"><div className="h-20 animate-pulse rounded-xl bg-slate-200"/><div className="grid gap-4 md:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="h-32 animate-pulse rounded-xl bg-slate-200"/>)}</div></div>;
  if (dashboard.error || !dashboard.data) return <Alert title="Inventory dashboard unavailable">{apiErrorMessage(dashboard.error)}</Alert>;
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-indigo-600">Inventory & Asset Management</p><h1 className="mt-2 text-2xl font-bold text-slate-900">Inventory Dashboard</h1><p className="mt-1 text-sm text-slate-500">Real-time stock health, asset custody, valuation, and transfer workload.</p></div><div className="flex flex-wrap gap-2 text-sm font-semibold"><Link className="rounded-md border bg-white px-3 py-2 text-slate-700" to="/inventory/stock-movements">Post movement</Link><Link className="rounded-md bg-indigo-600 px-3 py-2 text-white" to="/inventory/transfers">Create transfer</Link></div></header>
    <InventoryStatistics data={dashboard.data}/><div className="grid gap-6 xl:grid-cols-2"><section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Asset status</h2><div className="mt-4 space-y-3">{dashboard.data.asset_statuses.map((item)=><div key={item.status} className="flex items-center justify-between"><InventoryStatusBadge status={item.status}/><span className="font-semibold tabular-nums">{item.total}</span></div>)}</div></section><section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Warehouse stock value</h2><div className="mt-4 space-y-3">{dashboard.data.warehouse_stock.map((item)=><div key={item.id}><div className="flex justify-between text-sm"><span className="text-slate-600">{item.name}</span><span className="font-semibold tabular-nums">PKR {Number(item.stock_value).toLocaleString()}</span></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-indigo-500" style={{width:`${Math.max(4,Math.min(100,Number(item.stock_value)/(Math.max(...dashboard.data.warehouse_stock.map(x=>Number(x.stock_value)),1))*100))}%`}}/></div></div>)}</div></section></div>
    <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><h2 className="font-semibold text-slate-900">Recent movements</h2><Link to="/inventory/stock-movements" className="text-sm font-semibold text-indigo-600">View all</Link></div><div className="mt-4 divide-y">{dashboard.data.recent_movements.map((movement)=><div key={movement.id} className="flex items-center justify-between py-3"><div><p className="font-mono text-sm font-semibold text-slate-800">{movement.movement_number}</p><p className="text-xs capitalize text-slate-500">{movement.movement_type.replaceAll('_',' ')} · {movement.reason||'No reason entered'}</p></div><time className="text-xs text-slate-400">{new Date(movement.occurred_at).toLocaleString()}</time></div>)}</div></section>
  </div>;
};
