export interface CompanySettings { id?: number; company_name: string; legal_name?: string | null; registration_number?: string | null; tax_number?: string | null; address_line_1?: string | null; address_line_2?: string | null; city?: string | null; state?: string | null; postal_code?: string | null; country?: string | null; phone?: string | null; email?: string | null; website?: string | null; logo_path?: string | null; favicon_path?: string | null; timezone: string; currency_code: string; date_format: string; language_code: string; status?: string }
export interface Branch { id: number; code: string; name: string; description?: string | null; city?: string | null; phone?: string | null; email?: string | null; status: 'active' | 'inactive'; timezone?: string | null }
export interface Department { id: number; branch_id?: number | null; code: string; name: string; description?: string | null; status: 'active' | 'inactive' }
export interface SystemSettings { id?: number; application_name: string; environment_name: string; maintenance_mode: number | boolean; maintenance_message?: string | null; session_timeout_minutes: number; password_policy: Record<string, unknown>; mfa_policy?: Record<string, unknown>; file_upload_limits: Record<string, unknown>; email_settings?: Record<string, unknown>; sms_provider_settings?: Record<string, unknown>; cache_settings?: Record<string, unknown>; logging_settings?: Record<string, unknown> }
export interface BrandingSettings { id?: number; theme: string; primary_color: string; secondary_color: string; logo_path?: string | null; favicon_path?: string | null; login_background_path?: string | null; login_headline?: string | null; login_subheadline?: string | null; footer_text?: string | null }
export interface LocalizationSettings { id?: number; default_language: string; supported_languages: string[]; default_timezone: string; supported_timezones: string[]; default_currency: string; supported_currencies: string[]; date_format: string; time_format: string; number_format: Record<string, unknown>; first_day_of_week: number }
export interface NotificationSettings { id?: number; email_enabled: number | boolean; sms_enabled: number | boolean; in_app_enabled: number | boolean; alert_preferences: Record<string, boolean>; reminder_preferences: Record<string, boolean>; email_templates_enabled: number | boolean; sms_provider_placeholder?: Record<string, unknown> }
export interface SystemDashboard { active_branches: number; active_departments: number; system_health: { status: string; label: string }; configuration_status: { complete: boolean; missing: string[]; message: string } }
export interface ApiResource<T> { data: { id: string; attributes: T } }
export interface ApiCollection<T> { data: Array<{ id: string; attributes: T }>; meta?: { current_page: number; per_page: number; total: number; last_page: number } }
