import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';

import { Alert } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { usePermissions } from '@/hooks/usePermissions';
import { apiErrorMessage } from '@/lib/apiClient';

import { deleteRouter, discoverRouter, getRouter, getRouterHealth, setRouterEnabled, testSavedRouterConnection } from '../api/mikrotikApi';
import { RouterStatistics } from '../components/RouterStatistics';
import { RouterStatusBadge } from '../components/RouterStatusBadge';

export const RouterDetailPage = () => {
  const { id } = useParams<{ id: string }>();
  const routerId = Number(id);
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { can } = usePermissions();
  const router = useQuery({ queryKey: ['mikrotik', 'router', id], queryFn: () => getRouter(routerId) });
  const health = useQuery({ queryKey: ['mikrotik', 'router', id, 'health'], queryFn: () => getRouterHealth(routerId) });
  const discovery = useMutation({ mutationFn: () => discoverRouter(routerId), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['mikrotik', 'router', id] }); queryClient.invalidateQueries({ queryKey: ['mikrotik', 'routers'] }); } });
  const test = useMutation({ mutationFn: () => testSavedRouterConnection(routerId), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['mikrotik', 'router', id] }); queryClient.invalidateQueries({ queryKey: ['mikrotik', 'routers'] }); } });
  const toggle = useMutation({ mutationFn: () => setRouterEnabled(routerId, !router.data?.is_enabled), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['mikrotik', 'router', id] }); queryClient.invalidateQueries({ queryKey: ['mikrotik', 'routers'] }); } });
  const remove = useMutation({ mutationFn: () => deleteRouter(routerId), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['mikrotik', 'routers'] }); navigate('/network/routers'); } });
  if (router.isLoading) return <div className="h-80 animate-pulse rounded-xl bg-slate-100" />;
  if (router.error || !router.data) return <Alert title="Router unavailable" variant="danger">{apiErrorMessage(router.error, 'The requested router was not found.')}</Alert>;
  const item = router.data;
  const error = discovery.error ?? test.error ?? toggle.error ?? remove.error;

  return <div className="space-y-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><Link to="/network/routers" className="text-sm font-semibold text-indigo-600">← MikroTik Routers</Link><div className="mt-3 flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold text-slate-900">{item.name}</h1><RouterStatusBadge status={item.last_connection_status} /></div><p className="mt-1 font-mono text-sm text-slate-500">{item.host}:{item.api_port} · {item.api_username}</p></div><div className="flex flex-wrap gap-2">{can('mikrotik.connect') ? <><Button variant="secondary" onClick={() => test.mutate()} isLoading={test.isPending} disabled={!item.is_enabled}>Test connection</Button><Button variant="secondary" onClick={() => discovery.mutate()} isLoading={discovery.isPending} disabled={!item.is_enabled}>Discover</Button></> : null}{can('mikrotik.update') ? <><Button variant="secondary" onClick={() => navigate(`/network/routers/${item.id}/edit`)}>Edit</Button><Button variant={item.is_enabled ? 'danger' : 'secondary'} onClick={() => toggle.mutate()} isLoading={toggle.isPending}>{item.is_enabled ? 'Disable' : 'Enable'}</Button></> : null}</div></div>
    {error ? <Alert title="Router operation failed" variant="danger">{apiErrorMessage(error)}</Alert> : null}
    {test.data ? <Alert title="Connection successful" variant="success">{test.data.identity ?? item.name} responded in {test.data.latency_ms.toFixed(1)} ms.</Alert> : null}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-6"><section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-slate-900">Router discovery</h2><p className="mt-1 text-sm text-slate-500">Read-only system, interface, address, user, and queue information.</p></div>{discovery.data ? <span className="text-xs text-emerald-700">Refreshed now</span> : null}</div>{discovery.data ? <><dl className="mt-5 grid gap-4 sm:grid-cols-3"><div><dt className="text-xs text-slate-500">Identity</dt><dd className="mt-1 font-semibold">{discovery.data.identity ?? 'Unavailable'}</dd></div><div><dt className="text-xs text-slate-500">RouterOS</dt><dd className="mt-1 font-semibold">{discovery.data.routeros_version ?? 'Unavailable'}</dd></div><div><dt className="text-xs text-slate-500">Model</dt><dd className="mt-1 font-semibold">{discovery.data.model ?? 'Unavailable'}</dd></div></dl><div className="mt-6 grid gap-5 lg:grid-cols-2"><div><h3 className="text-sm font-semibold text-slate-800">Interfaces ({discovery.data.interfaces.length})</h3><div className="mt-2 max-h-64 overflow-auto rounded-lg border border-slate-200">{discovery.data.interfaces.map((networkInterface) => <div key={networkInterface.id ?? networkInterface.name} className="flex justify-between border-b border-slate-100 px-3 py-2 text-sm last:border-0"><span>{networkInterface.name ?? 'Unknown'} <span className="text-xs text-slate-400">{networkInterface.type}</span></span><span className={networkInterface.running ? 'text-emerald-700' : 'text-slate-500'}>{networkInterface.running ? 'Running' : 'Down'}</span></div>)}</div></div><div><h3 className="text-sm font-semibold text-slate-800">IP addresses ({discovery.data.ip_addresses.length})</h3><div className="mt-2 max-h-64 overflow-auto rounded-lg border border-slate-200">{discovery.data.ip_addresses.map((address) => <div key={address.id ?? address.address} className="flex justify-between border-b border-slate-100 px-3 py-2 font-mono text-sm last:border-0"><span>{address.address}</span><span className="font-sans text-xs text-slate-500">{address.interface}</span></div>)}</div></div></div></> : <p className="mt-5 rounded-lg bg-slate-50 p-4 text-sm text-slate-500">Select Discover to retrieve the latest RouterOS inventory. Discovery results are not used to modify router configuration.</p>}</section><section><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold text-slate-900">Latest health</h2><p className="mt-1 text-sm text-slate-500">Cached monitoring snapshot; refresh it from the health page.</p></div><Link className="text-sm font-semibold text-indigo-600" to={`/network/routers/${item.id}/health`}>Open health →</Link></div><RouterStatistics health={health.data ?? null} /></section></div>
      <aside className="space-y-6"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Configuration</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-slate-500">Site</dt><dd className="mt-1 font-medium">{item.site ?? '—'}</dd></div><div><dt className="text-slate-500">Location</dt><dd className="mt-1 font-medium">{item.location ?? '—'}</dd></div><div><dt className="text-slate-500">Group</dt><dd className="mt-1 font-medium">{item.router_group_name ?? 'Ungrouped'}</dd></div><div><dt className="text-slate-500">Tags</dt><dd className="mt-1 flex flex-wrap gap-1">{item.tags.length ? item.tags.map((tag) => <span key={tag.id} className="rounded bg-slate-100 px-2 py-1 text-xs">{tag.name}</span>) : '—'}</dd></div><div><dt className="text-slate-500">Last successful connection</dt><dd className="mt-1 font-medium">{item.last_connected_at ? new Date(item.last_connected_at).toLocaleString() : 'Never'}</dd></div></dl></section>{item.notes ? <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Notes</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.notes}</p></section> : null}{can('mikrotik.delete') ? <Button variant="danger" className="w-full" onClick={() => { if (window.confirm(`Delete ${item.name}? This does not alter the physical router.`)) remove.mutate(); }} isLoading={remove.isPending}>Delete router</Button> : null}</aside>
    </div>
  </div>;
};
