<?php
declare(strict_types=1);
namespace SkyFi\FieldService\Validators;
use SkyFi\FieldService\DTOs\{InstallationRequestData,TechnicianData,WorkOrderData};
use SkyFi\Shared\Exceptions\ValidationException;
final class FieldServiceValidator
{
    public const TYPES=['installation','maintenance','repair','equipment_replacement','relocation','site_survey','disconnection'];
    public const PRIORITIES=['low','normal','high','urgent'];
    public const STATUSES=['pending','assigned','scheduled','in_progress','on_hold','completed','failed','cancelled'];
    private const TRANSITIONS=['pending'=>['assigned','scheduled','cancelled'],'assigned'=>['scheduled','pending','cancelled'],'scheduled'=>['assigned','in_progress','on_hold','cancelled'],'in_progress'=>['on_hold','completed','failed'],'on_hold'=>['scheduled','in_progress','failed','cancelled'],'failed'=>['scheduled'],'completed'=>[],'cancelled'=>[]];
    public function request(InstallationRequestData $d):void {$e=[];if($d->customerId<1)$e[]=$this->err('customer_id','A customer is required.');if($d->connectionId<1)$e[]=$this->err('connection_id','A connection is required.');if($d->serviceAddress==='')$e[]=$this->err('service_address','A service address is required.');if(!in_array($d->priority,self::PRIORITIES,true))$e[]=$this->err('priority','Priority is invalid.');if(!in_array($d->source,['manual','connection_approval','system'],true))$e[]=$this->err('source','Source is invalid.');$this->range($d->preferredStartAt,$d->preferredEndAt,'preferred',$e);$this->throw($e);}
    public function order(WorkOrderData $d):void {$v=$d->values;$e=[];if(($v['customer_id']??0)<1)$e[]=$this->err('customer_id','A customer is required.');if(!in_array($v['type']??'',self::TYPES,true))$e[]=$this->err('type','Work order type is invalid.');if(!in_array($v['priority']??'',self::PRIORITIES,true))$e[]=$this->err('priority','Priority is invalid.');if(($v['title']??'')==='')$e[]=$this->err('title','A title is required.');if(($v['service_address']??'')==='')$e[]=$this->err('service_address','A service address is required.');if(($v['estimated_duration_minutes']??0)<1)$e[]=$this->err('estimated_duration_minutes','Duration must be greater than zero.');$this->range($v['scheduled_start_at']??null,$v['scheduled_end_at']??null,'scheduled',$e);$this->throw($e);}
    public function technician(TechnicianData $d):void {$e=[];if($d->userId<1)$e[]=$this->err('user_id','A staff user is required.');if(trim($d->employeeCode)==='')$e[]=$this->err('employee_code','Employee code is required.');if(!in_array($d->status,['active','inactive','on_leave'],true))$e[]=$this->err('status','Technician status is invalid.');if($d->maxDailyJobs<1||$d->maxDailyJobs>30)$e[]=$this->err('max_daily_jobs','Daily job capacity must be between 1 and 30.');$this->throw($e);}
    public function transition(string $from,string $to):void {if(!in_array($to,self::TRANSITIONS[$from]??[],true))$this->throw([$this->err('status',"Cannot move a work order from {$from} to {$to}.")]);}
    public function schedule(int $technicianId,?string $start,?string $end):void {$e=[];if($technicianId<1)$e[]=$this->err('technician_id','An active technician is required.');$this->range($start,$end,'scheduled',$e,true);$this->throw($e);}
    public function material(array $d):void {$e=[];if((int)($d['product_id']??0)<1)$e[]=$this->err('product_id','A product is required.');if(!is_numeric($d['quantity_planned']??null)||(float)$d['quantity_planned']<0)$e[]=$this->err('quantity_planned','Planned quantity cannot be negative.');if(!is_numeric($d['quantity_used']??null)||(float)$d['quantity_used']<0)$e[]=$this->err('quantity_used','Used quantity cannot be negative.');$this->throw($e);}
    private function range(?string $start,?string $end,string $field,array &$errors,bool $required=false):void {if($required&&(!$start||!$end)){$errors[]=$this->err($field.'_start_at','Start and end times are required.');return;}if($start&&$end&&strtotime($end)<=strtotime($start))$errors[]=$this->err($field.'_end_at','End time must be after start time.');}
    private function err(string $f,string $d):array{return ['code'=>'validation_error','detail'=>$d,'source'=>['pointer'=>'/data/attributes/'.$f]];} private function throw(array $e):void{if($e)throw new ValidationException($e);}
}
