<?php declare(strict_types=1);
namespace SkyFi\System\Services;
use SkyFi\Rbac\Contracts\AuditLoggerContract;
use SkyFi\System\Repositories\{PdoBranchRepository,PdoBrandingRepository,PdoCompanyRepository,PdoDepartmentRepository,PdoLocalizationRepository,PdoNotificationPreferenceRepository,PdoSystemSettingsRepository};
use SkyFi\System\Validators\SystemValidator;
final class SystemAdministrationService
{
    public function __construct(public readonly PdoCompanyRepository $companies, public readonly PdoBranchRepository $branches, public readonly PdoDepartmentRepository $departments, public readonly PdoSystemSettingsRepository $settings, public readonly PdoBrandingRepository $branding, public readonly PdoLocalizationRepository $localization, public readonly PdoNotificationPreferenceRepository $notifications, private readonly SystemValidator $validator, private readonly AuditLoggerContract $audit) {}
    public function updateCompany(array $d,int $u,string $ip,string $ua): array { $this->validator->company($d); $old=$this->companies->first(); $new=$this->companies->update($d,$u); $this->audit->log($u,'system.company.updated','company',(int)$new['id'],$old,$new,$ip,$ua); return $new; }
    public function saveBranch(?int $id,array $d,int $u,string $ip,string $ua): array { $this->validator->branch($d); $old=$id?$this->branches->find($id):null; $new=$id?$this->branches->update($id,$d,$u):$this->branches->create($d,$u); $this->audit->log($u,$id?'system.branch.updated':'system.branch.created','branch',(int)$new['id'],$old,$new,$ip,$ua); return $new; }
    public function deleteBranch(int $id,int $u,string $ip,string $ua): void { $old=$this->branches->find($id); $this->branches->delete($id); $this->audit->log($u,'system.branch.deleted','branch',$id,$old,null,$ip,$ua); }
    public function branchStatus(int $id,string $status,int $u,string $ip,string $ua): array { $old=$this->branches->find($id); $new=$this->branches->status($id,$status,$u); $this->audit->log($u,'system.branch.status_changed','branch',$id,$old,$new,$ip,$ua); return $new; }
    public function saveDepartment(?int $id,array $d,int $u,string $ip,string $ua): array { $this->validator->department($d); $old=$id?$this->departments->find($id):null; $new=$id?$this->departments->update($id,$d,$u):$this->departments->create($d,$u); $this->audit->log($u,$id?'system.department.updated':'system.department.created','department',(int)$new['id'],$old,$new,$ip,$ua); return $new; }
    public function deleteDepartment(int $id,int $u,string $ip,string $ua): void { $old=$this->departments->find($id); $this->departments->delete($id); $this->audit->log($u,'system.department.deleted','department',$id,$old,null,$ip,$ua); }
    public function departmentStatus(int $id,string $status,int $u,string $ip,string $ua): array { $old=$this->departments->find($id); $new=$this->departments->status($id,$status,$u); $this->audit->log($u,'system.department.status_changed','department',$id,$old,$new,$ip,$ua); return $new; }
    public function updateSettings(array $d,int $u,string $ip,string $ua): array { $this->validator->system($d); $old=$this->settings->first(); $new=$this->settings->update($d,$u); $this->audit->log($u,'system.settings.updated','system_settings',(int)$new['id'],$old,$new,$ip,$ua); return $new; }
    public function updateBranding(array $d,int $u,string $ip,string $ua): array { $this->validator->branding($d); $old=$this->branding->first(); $new=$this->branding->update($d,$u); $this->audit->log($u,'system.branding.updated','branding_settings',(int)$new['id'],$old,$new,$ip,$ua); return $new; }
    public function updateLocalization(array $d,int $u,string $ip,string $ua): array { $this->validator->localization($d); $old=$this->localization->first(); $new=$this->localization->update($d,$u); $this->audit->log($u,'system.localization.updated','localization_settings',(int)$new['id'],$old,$new,$ip,$ua); return $new; }
    public function updateNotifications(array $d,int $u,string $ip,string $ua): array { $this->validator->notifications($d); $old=$this->notifications->first(); $new=$this->notifications->update($d,$u); $this->audit->log($u,'system.notifications.updated','notification_preferences',(int)$new['id'],$old,$new,$ip,$ua); return $new; }
}
