import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { systemApi } from './systemApi';
import type { Branch, BrandingSettings, CompanySettings, Department, LocalizationSettings, NotificationSettings, SystemSettings } from '../types';
export const useSystemDashboard = () => useQuery({ queryKey: ['system', 'dashboard'], queryFn: systemApi.dashboard });
export const useCompanySettings = () => useQuery({ queryKey: ['system', 'company'], queryFn: systemApi.company });
export const useBranches = (filters: Record<string, unknown> = {}) => useQuery({ queryKey: ['system', 'branches', filters], queryFn: () => systemApi.branches(filters) });
export const useDepartments = (filters: Record<string, unknown> = {}) => useQuery({ queryKey: ['system', 'departments', filters], queryFn: () => systemApi.departments(filters) });
export const useSystemSettings = () => useQuery({ queryKey: ['system', 'settings'], queryFn: systemApi.settings });
export const useBrandingSettings = () => useQuery({ queryKey: ['system', 'branding'], queryFn: systemApi.branding });
export const useLocalizationSettings = () => useQuery({ queryKey: ['system', 'localization'], queryFn: systemApi.localization });
export const useLocalizationOptions = () => useQuery({ queryKey: ['system', 'localization-options'], queryFn: systemApi.localizationOptions, staleTime: 300000 });
export const useNotificationSettings = () => useQuery({ queryKey: ['system', 'notifications'], queryFn: systemApi.notifications });
const useSystemMutation = <T,>(fn: (data: T) => Promise<unknown>) => { const client = useQueryClient(); return useMutation({ mutationFn: fn, onSuccess: () => void client.invalidateQueries({ queryKey: ['system'] }) }); };
export const useUpdateCompanySettings = () => useSystemMutation<Partial<CompanySettings>>(systemApi.updateCompany);
export const useSaveBranch = (id?: number) => useSystemMutation<Partial<Branch>>((data) => id ? systemApi.updateBranch(id, data) : systemApi.createBranch(data));
export const useDeleteBranch = () => useSystemMutation<number>(systemApi.deleteBranch);
export const useToggleBranchStatus = () => useSystemMutation<{ id: number; status: 'active' | 'inactive' }>((d) => systemApi.setBranchStatus(d.id, d.status));
export const useSaveDepartment = (id?: number) => useSystemMutation<Partial<Department>>((data) => id ? systemApi.updateDepartment(id, data) : systemApi.createDepartment(data));
export const useDeleteDepartment = () => useSystemMutation<number>(systemApi.deleteDepartment);
export const useToggleDepartmentStatus = () => useSystemMutation<{ id: number; status: 'active' | 'inactive' }>((d) => systemApi.setDepartmentStatus(d.id, d.status));
export const useUpdateSystemSettings = () => useSystemMutation<Partial<SystemSettings>>(systemApi.updateSettings);
export const useUpdateBrandingSettings = () => useSystemMutation<Partial<BrandingSettings>>(systemApi.updateBranding);
export const useUploadBrandingAsset = () => { const client = useQueryClient(); return useMutation({ mutationFn: ({ file, type }: { file: File; type: string }) => systemApi.uploadBrandingAsset(file, type), onSuccess: () => void client.invalidateQueries({ queryKey: ['system', 'branding'] }) }); };
export const useUpdateLocalizationSettings = () => useSystemMutation<Partial<LocalizationSettings>>(systemApi.updateLocalization);
export const useUpdateNotificationSettings = () => useSystemMutation<Partial<NotificationSettings>>(systemApi.updateNotifications);
