<?php
declare(strict_types=1);
namespace SkyFi\FieldService\Controllers;
use SkyFi\FieldService\DTOs\{FieldServiceListFilters,InstallationRequestData,WorkOrderData};
use SkyFi\FieldService\Services\{FieldServiceDashboardService,InstallationRequestService,SchedulerService,WorkOrderService};
use SkyFi\Rbac\Middleware\RequirePermissionMiddleware;
use SkyFi\Shared\Http\{ApiResponse,Request,Response};
final class FieldServiceController
{
 public function __construct(private readonly InstallationRequestService$requests,private readonly WorkOrderService$orders,private readonly SchedulerService$scheduler,private readonly FieldServiceDashboardService$dashboard,private readonly RequirePermissionMiddleware$auth){}
 public function dashboard(Request$r):Response{$this->can($r,'field.view');return new Response(200,['data'=>$this->dashboard->dashboard()]);}
 public function requests(Request$r):Response{$this->can($r,'field.view');return$this->collection($this->requests->list(FieldServiceListFilters::fromQuery($r->query())),'installation-requests');} public function request(Request$r):Response{$this->can($r,'field.view');$x=$this->requests->get($this->id($r));return ApiResponse::resource('installation-requests',(string)$x['id'],$x);} public function createRequest(Request$r):Response{$a=$this->can($r,'field.create');$x=$this->requests->create(InstallationRequestData::fromArray($r->body()),$a);return ApiResponse::resource('installation-requests',(string)$x['id'],$x,201);} public function updateRequest(Request$r):Response{$a=$this->can($r,'field.update');$x=$this->requests->update($this->id($r),InstallationRequestData::fromArray($r->body()),$a);return ApiResponse::resource('installation-requests',(string)$x['id'],$x);} public function deleteRequest(Request$r):Response{$a=$this->can($r,'field.manage');$this->requests->delete($this->id($r),$a);return ApiResponse::noContent();}
 public function requestAction(Request$r):Response{$action=$this->param($r,'action');$permission=in_array($action,['assign','schedule','reschedule'],true)?'field.assign':($action==='complete'?'field.complete':($action==='create-work-order'?'field.create':'field.manage'));$a=$this->can($r,$permission);$b=$r->body();$x=match($action){'assign'=>$this->requests->assign($this->id($r),(int)($b['technician_id']??0),$a),'schedule','reschedule'=>$this->requests->schedule($this->id($r),$b,$a),'cancel'=>$this->requests->cancel($this->id($r),(string)($b['reason']??''),$a),'complete'=>$this->requests->complete($this->id($r),$a),'create-work-order'=>$this->orders->createFromRequest($this->requests->get($this->id($r)),$a),default=>throw new \SkyFi\Shared\Exceptions\NotFoundException('Installation action not found.')};return ApiResponse::resource($action==='create-work-order'?'work-orders':'installation-requests',(string)$x['id'],$x);}
 public function orders(Request$r):Response{$this->can($r,'field.view');return$this->collection($this->orders->list(FieldServiceListFilters::fromQuery($r->query())),'work-orders');} public function order(Request$r):Response{$this->can($r,'field.view');$x=$this->orders->get($this->id($r));return ApiResponse::resource('work-orders',(string)$x['id'],$x);} public function createOrder(Request$r):Response{$a=$this->can($r,'field.create');$x=$this->orders->create(WorkOrderData::fromArray($r->body()),$a);return ApiResponse::resource('work-orders',(string)$x['id'],$x,201);} public function updateOrder(Request$r):Response{$a=$this->can($r,'field.update');$x=$this->orders->update($this->id($r),WorkOrderData::fromArray($r->body()),$a);return ApiResponse::resource('work-orders',(string)$x['id'],$x);} public function deleteOrder(Request$r):Response{$a=$this->can($r,'field.manage');$this->orders->delete($this->id($r),$a);return ApiResponse::noContent();}
 public function orderAction(Request$r):Response{$action=$this->param($r,'action');$permission=match($action){'assign','schedule','reschedule'=>'field.assign','complete'=>'field.complete','cancel'=>'field.manage',default=>'field.update'};$a=$this->can($r,$permission);$b=$r->body();$x=match($action){'assign'=>$this->orders->assign($this->id($r),$b,$a),'schedule','reschedule'=>$this->orders->schedule($this->id($r),$b,$a),'complete'=>$this->orders->complete($this->id($r),$b,$a),'cancel'=>$this->orders->transition($this->id($r),'cancelled',$b,$a),default=>$this->orders->transition($this->id($r),(string)($b['status']??$action),$b,$a)};return ApiResponse::resource('work-orders',(string)$x['id'],$x);}
 public function timeline(Request$r):Response{$this->can($r,'field.view');return new Response(200,['data'=>$this->orders->get($this->id($r))['timeline']]);} public function schedule(Request$r):Response{$this->can($r,'field.view');return new Response(200,['data'=>$this->scheduler->schedule($r->query())]);} public function unscheduled(Request$r):Response{$this->can($r,'field.view');return new Response(200,['data'=>$this->scheduler->unscheduled()['items']]);}
 private function can(Request$r,string$p):int{$a=(int)($r->attributes()['claims']['sub']??0);$this->auth->authorize($a,$p);return$a;}private function id(Request$r):int{return(int)$this->param($r,'id');}private function param(Request$r,string$k):string{return(string)($r->attributes()['route_params'][$k]??'');}private function collection(array$x,string$type):Response{return new Response(200,['data'=>array_map(fn($i)=>['type'=>$type,'id'=>(string)$i['id'],'attributes'=>$i],$x['items']),'meta'=>['current_page'=>$x['page'],'per_page'=>$x['perPage'],'total'=>$x['total'],'last_page'=>$x['lastPage']]]);}
}
