<?php
declare(strict_types=1);
namespace SkyFi\FieldService\Controllers;
use SkyFi\FieldService\Contracts\FieldServiceRepositoryContract;
use SkyFi\FieldService\DTOs\{FieldServiceListFilters,TechnicianData};
use SkyFi\FieldService\Services\TechnicianService;
use SkyFi\Rbac\Middleware\RequirePermissionMiddleware;
use SkyFi\Shared\Http\{ApiResponse,Request,Response};
final class TechnicianController
{
 public function __construct(private readonly TechnicianService$service,private readonly FieldServiceRepositoryContract$repo,private readonly RequirePermissionMiddleware$auth){}
 public function index(Request$r):Response{$this->can($r,'field.view');$x=$this->service->list(FieldServiceListFilters::fromQuery($r->query()));return new Response(200,['data'=>array_map(fn($i)=>['type'=>'technicians','id'=>(string)$i['id'],'attributes'=>$i],$x['items']),'meta'=>['current_page'=>$x['page'],'per_page'=>$x['perPage'],'total'=>$x['total'],'last_page'=>$x['lastPage']]]);} public function show(Request$r):Response{$this->can($r,'field.view');$x=$this->service->get($this->id($r));return ApiResponse::resource('technicians',(string)$x['id'],$x);} public function store(Request$r):Response{$a=$this->can($r,'field.manage');$x=$this->service->create(TechnicianData::fromArray($r->body()),$a);return ApiResponse::resource('technicians',(string)$x['id'],$x,201);}public function update(Request$r):Response{$a=$this->can($r,'field.manage');$x=$this->service->update($this->id($r),TechnicianData::fromArray($r->body()),$a);return ApiResponse::resource('technicians',(string)$x['id'],$x);}public function destroy(Request$r):Response{$a=$this->can($r,'field.manage');$this->service->delete($this->id($r),$a);return ApiResponse::noContent();}
 public function schedule(Request$r):Response{$this->can($r,'field.view');return new Response(200,['data'=>$this->service->schedule($this->id($r),$r->query())]);}public function relation(Request$r):Response{$this->can($r,'field.view');return new Response(200,['data'=>$this->service->relations($this->id($r),$this->resource($r))]);}public function addRelation(Request$r):Response{$a=$this->can($r,'field.manage');return new Response(201,['data'=>$this->service->addRelation($this->id($r),$this->resource($r),$r->body(),$a)]);}public function updateRelation(Request$r):Response{$a=$this->can($r,'field.manage');$x=$this->service->updateRelation($this->id($r),$this->resource($r),(int)($r->attributes()['route_params']['relationId']??0),$r->body(),$a);return new Response(200,['data'=>$x]);}public function deleteRelation(Request$r):Response{$a=$this->can($r,'field.manage');$this->service->deleteRelation($this->id($r),$this->resource($r),(int)($r->attributes()['route_params']['relationId']??0),$a);return ApiResponse::noContent();}public function lookup(Request$r):Response{$this->can($r,'field.view');return new Response(200,['data'=>$this->repo->lookup((string)($r->attributes()['route_params']['resource']??''),(string)($r->query()['search']??''))]);}
 private function can(Request$r,string$p):int{$a=(int)($r->attributes()['claims']['sub']??0);$this->auth->authorize($a,$p);return$a;}private function id(Request$r):int{return(int)($r->attributes()['route_params']['id']??0);}private function resource(Request$r):string{return(string)($r->attributes()['route_params']['resource']??'');}
}
