import { zodResolver } from '@hookform/resolvers/zod';
import { useFieldArray, useForm } from 'react-hook-form';
import { Button } from '@/components/ui/button';
import { stockOperationSchema, type StockOperationSchemaValues } from '../schemas';
import type { Asset, Product } from '../types';

const control = 'h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-500';
export const StockMovementForm = ({ operation, products, locations, assets, onSubmit, onCancel, isLoading }: { operation: string; products: Product[]; locations: Array<Record<string, unknown>>; assets: Asset[]; onSubmit: (data: StockOperationSchemaValues) => void; onCancel: () => void; isLoading?: boolean }) => {
  const form = useForm<StockOperationSchemaValues>({ resolver: zodResolver(stockOperationSchema), defaultValues: { reference_type: '', reference_number: '', reason: '', notes: '', lines: [{ product_id: 0, quantity: 1, source_location_id: undefined, destination_location_id: undefined, source_condition: 'available', destination_condition: operation === 'damaged' ? 'damaged' : 'available', unit_cost: 0, asset_ids: [] }] } });
  const rows = useFieldArray({ control: form.control, name: 'lines' });
  const watched = form.watch('lines');
  const needsSource = ['stock-out', 'adjustment-out', 'damaged', 'scrap'].includes(operation);
  const needsDestination = ['stock-in', 'opening-balance', 'adjustment-in', 'return', 'damaged'].includes(operation);
  return <form className="space-y-5" onSubmit={form.handleSubmit(onSubmit)}><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Reference type<input className={`mt-1 ${control}`} {...form.register('reference_type')} /></label><label className="text-xs font-semibold text-slate-600">Reference number<input className={`mt-1 ${control}`} {...form.register('reference_number')} /></label>{['adjustment-in', 'adjustment-out', 'damaged', 'scrap'].includes(operation) && <label className="text-xs font-semibold text-slate-600 sm:col-span-2">Reason<input className={`mt-1 ${control}`} {...form.register('reason')} /></label>}</div>
    <fieldset><legend className="text-sm font-semibold text-slate-900">Stock lines</legend><div className="mt-3 space-y-3">{rows.fields.map((row, index) => { const product = products.find((item) => item.id === Number(watched[index]?.product_id)); const source = Number(watched[index]?.source_location_id || 0); return <div key={row.id} className="grid gap-3 rounded-lg border bg-slate-50 p-3 md:grid-cols-[2fr_1.2fr_0.8fr_0.8fr_auto]">
      <select className={control} aria-label={`Product ${index + 1}`} {...form.register(`lines.${index}.product_id`, { valueAsNumber: true })}><option value={0}>Select product</option>{products.map((item) => <option key={item.id} value={item.id}>{item.sku} · {item.name}</option>)}</select>
      {needsSource ? <select className={control} aria-label={`Source ${index + 1}`} {...form.register(`lines.${index}.source_location_id`, { setValueAs: (value) => value === '' ? undefined : Number(value) })}><option value="">Source location</option>{locations.map((location) => <option key={String(location.id)} value={Number(location.id)}>{String(location.label)}</option>)}</select> : <span />}
      {needsDestination ? <select className={control} aria-label={`Destination ${index + 1}`} {...form.register(`lines.${index}.destination_location_id`, { setValueAs: (value) => value === '' ? undefined : Number(value) })}><option value="">Destination</option>{locations.map((location) => <option key={String(location.id)} value={Number(location.id)}>{String(location.label)}</option>)}</select> : <span />}
      <input className={control} aria-label={`Quantity ${index + 1}`} type="number" min="0.0001" step="0.0001" {...form.register(`lines.${index}.quantity`, { valueAsNumber: true })} />
      <Button type="button" variant="ghost" onClick={() => rows.remove(index)} disabled={rows.fields.length === 1}>Remove</Button>
      {product?.tracking_mode === 'quantity' && !needsSource && <label className="text-xs font-semibold text-slate-600 md:col-span-2">Unit cost<input className={`mt-1 ${control}`} type="number" min="0" step="0.0001" {...form.register(`lines.${index}.unit_cost`, { valueAsNumber: true })} /></label>}
      {product?.tracking_mode === 'serialized' && <label className="text-xs font-semibold text-slate-600 md:col-span-5">Assets<select multiple className={`${control} mt-1 h-28 py-2`} {...form.register(`lines.${index}.asset_ids`)}>{assets.filter((asset) => asset.product_id === product.id && (['stock-in', 'opening-balance'].includes(operation) ? asset.current_assignment_id === null : (!source || asset.warehouse_location_id === source))).map((asset) => <option key={asset.id} value={asset.id}>{asset.asset_tag} · {asset.serial_number}</option>)}</select><span className="mt-1 block font-normal text-slate-400">Select exactly the number of serialized assets entered as quantity.</span></label>}
    </div>; })}</div><Button type="button" variant="secondary" className="mt-3" onClick={() => rows.append({ product_id: 0, quantity: 1, source_condition: 'available', destination_condition: operation === 'damaged' ? 'damaged' : 'available', unit_cost: 0, asset_ids: [] })}>Add line</Button></fieldset>
    <label className="block text-xs font-semibold text-slate-600">Notes<textarea className={`${control} mt-1 h-auto py-2`} rows={3} {...form.register('notes')} /></label>{form.formState.errors.lines && <p className="text-sm text-red-600">Review all stock lines and required locations.</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" isLoading={isLoading}>Post {operation.replaceAll('-', ' ')}</Button></div>
  </form>;
};
