<?php
declare(strict_types=1);
namespace SkyFi\FieldService\Repositories;
use PDO;
use SkyFi\FieldService\Contracts\FieldServiceRepositoryContract;
use SkyFi\FieldService\DTOs\FieldServiceListFilters;
use SkyFi\Shared\Exceptions\{NotFoundException,ValidationException};
final class PdoFieldServiceRepository implements FieldServiceRepositoryContract
{
    public function __construct(private readonly PDO $pdo){}
    public function listRequests(FieldServiceListFilters $f):array{return $this->paged('installation_requests','ir',$this->requestSelect(),$f,['status'=>'ir.status','priority'=>'ir.priority','customer_id'=>'ir.customer_id','connection_id'=>'ir.connection_id','technician_id'=>'ir.assigned_technician_id','source'=>'ir.source'],['ir.request_number','c.full_name','c.customer_code','cn.connection_number'],['created_at'=>'ir.created_at','status'=>'ir.status','priority'=>'ir.priority','scheduled_start_at'=>'ir.scheduled_start_at']);}
    public function findRequest(int $id):?array{$s=$this->pdo->prepare($this->requestSelect().' WHERE ir.id=? AND ir.deleted_at IS NULL');$s->execute([$id]);return $s->fetch()?:null;}
    public function findRequestByConnection(int $id):?array{$s=$this->pdo->prepare($this->requestSelect().' WHERE ir.connection_id=? AND ir.deleted_at IS NULL');$s->execute([$id]);return $s->fetch()?:null;}
    public function createRequest(array $d,int $actor):array{$d['request_number']=$this->number('IR');$d['created_by']=$actor;$id=$this->insert('installation_requests',$d);return $this->findRequest($id)??throw new \RuntimeException('Unable to load installation request.');}
    public function updateRequest(int $id,array $d,int $actor):array{$this->update('installation_requests',$id,$d+['updated_by'=>$actor]);return $this->findRequest($id)??throw new NotFoundException('Installation request not found.');}
    public function deleteRequest(int $id,int $actor):void{$this->softDelete('installation_requests',$id,$actor);}

    public function listOrders(FieldServiceListFilters $f):array{return $this->paged('work_orders','wo',$this->orderSelect(),$f,['status'=>'wo.status','type'=>'wo.type','priority'=>'wo.priority','customer_id'=>'wo.customer_id','connection_id'=>'wo.connection_id','technician_id'=>'wo.assigned_technician_id','team_id'=>'wo.field_team_id','scheduled_from'=>'wo.scheduled_start_at >=','scheduled_to'=>'wo.scheduled_start_at <='],['wo.work_order_number','wo.title','c.full_name','c.customer_code','cn.connection_number'],['created_at'=>'wo.created_at','work_order_number'=>'wo.work_order_number','status'=>'wo.status','priority'=>'wo.priority','scheduled_start_at'=>'wo.scheduled_start_at','completed_at'=>'wo.completed_at']);}
    public function findOrder(int $id,bool $lock=false):?array{$sql=$this->orderSelect().' WHERE wo.id=? AND wo.deleted_at IS NULL'.($lock?' FOR UPDATE':'');$s=$this->pdo->prepare($sql);$s->execute([$id]);return $s->fetch()?:null;}
    public function createOrder(array $d,int $actor):array{$d['work_order_number']=$this->number('WO');$d['created_by']=$actor;$id=$this->insert('work_orders',$d);return $this->findOrder($id)??throw new \RuntimeException('Unable to load work order.');}
    public function updateOrder(int $id,array $d,int $actor):array{$this->update('work_orders',$id,$d+['updated_by'=>$actor]);return $this->findOrder($id)??throw new NotFoundException('Work order not found.');}
    public function deleteOrder(int $id,int $actor):void{$this->softDelete('work_orders',$id,$actor);}

    public function listTechnicians(FieldServiceListFilters $f):array{return $this->paged('technicians','t',$this->technicianSelect(),$f,['status'=>'t.status','team_id'=>'t.field_team_id'],['t.employee_code','u.name','u.email','t.phone'],['created_at'=>'t.created_at','name'=>'u.name','employee_code'=>'t.employee_code','status'=>'t.status']);}
    public function findTechnician(int $id):?array{$s=$this->pdo->prepare($this->technicianSelect().' WHERE t.id=? AND t.deleted_at IS NULL');$s->execute([$id]);$row=$s->fetch();if(!$row)return null;$row['skills']=$this->technicianRelation($id,'skills');$row['service_areas']=$this->technicianRelation($id,'service-areas');$row['availability']=$this->technicianRelation($id,'availability');return $row;}
    public function createTechnician(array $d,int $actor):array{$d['created_by']=$actor;$id=$this->insert('technicians',$d);return $this->findTechnician($id)??throw new \RuntimeException('Unable to load technician.');}
    public function updateTechnician(int $id,array $d,int $actor):array{$this->update('technicians',$id,$d+['updated_by'=>$actor]);return $this->findTechnician($id)??throw new NotFoundException('Technician not found.');}
    public function deleteTechnician(int $id,int $actor):void{$this->softDelete('technicians',$id,$actor);}
    public function hasScheduleConflict(int $technicianId,string $start,string $end,?int $except=null):bool{$active=$this->scalar("SELECT 1 FROM technicians WHERE id=? AND status='active' AND deleted_at IS NULL",[$technicianId]);if(!$active)return true;$blocked=$this->scalar("SELECT 1 FROM technician_availability WHERE technician_id=? AND availability_type IN ('unavailable','leave') AND deleted_at IS NULL AND starts_at < ? AND ends_at > ? LIMIT 1",[$technicianId,$end,$start]);if($blocked)return true;$capacity=(int)$this->scalar('SELECT max_daily_jobs FROM technicians WHERE id=?',[$technicianId]);$daily=(int)$this->scalar("SELECT COUNT(*) FROM work_orders WHERE assigned_technician_id=? AND DATE(scheduled_start_at)=DATE(?) AND status IN ('assigned','scheduled','in_progress') AND deleted_at IS NULL".($except?' AND id<>?':''),$except?[$technicianId,$start,$except]:[$technicianId,$start]);if($daily>=$capacity)return true;$sql="SELECT 1 FROM work_orders WHERE assigned_technician_id=? AND deleted_at IS NULL AND status IN ('assigned','scheduled','in_progress') AND scheduled_start_at < ? AND scheduled_end_at > ?";$p=[$technicianId,$end,$start];if($except){$sql.=' AND id<>?';$p[]=$except;}$s=$this->pdo->prepare($sql.' LIMIT 1');$s->execute($p);return(bool)$s->fetchColumn();}
    public function schedule(array $filters):array{$where=['wo.deleted_at IS NULL','wo.scheduled_start_at IS NOT NULL'];$p=[];if(!empty($filters['from'])){$where[]='wo.scheduled_start_at>=?';$p[]=$filters['from'];}if(!empty($filters['to'])){$where[]='wo.scheduled_start_at<=?';$p[]=$filters['to'];}if(!empty($filters['technician_id'])){$where[]='wo.assigned_technician_id=?';$p[]=(int)$filters['technician_id'];}$s=$this->pdo->prepare($this->orderSelect().' WHERE '.implode(' AND ',$where).' ORDER BY wo.scheduled_start_at');$s->execute($p);return $s->fetchAll();}
    public function dashboard():array{$one=fn(string $q)=>(int)$this->pdo->query($q)->fetchColumn();return ['pending_installations'=>$one("SELECT COUNT(*) FROM installation_requests WHERE status IN ('pending','assigned','scheduled') AND deleted_at IS NULL"),'todays_work_orders'=>$one("SELECT COUNT(*) FROM work_orders WHERE DATE(scheduled_start_at)=UTC_DATE() AND deleted_at IS NULL"),'active_technicians'=>$one("SELECT COUNT(*) FROM technicians WHERE status='active' AND deleted_at IS NULL"),'completed_jobs'=>$one("SELECT COUNT(*) FROM work_orders WHERE status='completed' AND completed_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 30 DAY) AND deleted_at IS NULL"),'average_installation_hours'=>(float)($this->pdo->query("SELECT COALESCE(AVG(TIMESTAMPDIFF(MINUTE,created_at,completed_at))/60,0) FROM work_orders WHERE type='installation' AND status='completed' AND deleted_at IS NULL")->fetchColumn()),'material_usage'=>$this->pdo->query("SELECT p.name product_name,SUM(m.quantity_used) quantity_used FROM work_order_materials m JOIN inventory_products p ON p.id=m.product_id WHERE m.usage_status='used' AND m.deleted_at IS NULL GROUP BY p.id,p.name ORDER BY quantity_used DESC LIMIT 6")->fetchAll(),'recent_orders'=>$this->pdo->query($this->orderSelect()." WHERE wo.deleted_at IS NULL ORDER BY wo.updated_at DESC LIMIT 6")->fetchAll()];}

    public function materials(int $id):array{$s=$this->pdo->prepare("SELECT m.*,p.name product_name,p.sku,p.tracking_mode,a.asset_tag,a.serial_number,wl.code location_code,w.name warehouse_name FROM work_order_materials m JOIN inventory_products p ON p.id=m.product_id LEFT JOIN inventory_assets a ON a.id=m.asset_id LEFT JOIN warehouse_locations wl ON wl.id=m.warehouse_location_id LEFT JOIN warehouses w ON w.id=wl.warehouse_id WHERE m.work_order_id=? AND m.deleted_at IS NULL ORDER BY m.id");$s->execute([$id]);return $s->fetchAll();}
    public function saveMaterial(int $wo,?int $id,array $d,int $actor):array{$d['work_order_id']=$wo;if($id){unset($d['work_order_id']);$this->update('work_order_materials',$id,$d+['updated_by'=>$actor],['work_order_id'=>$wo]);}else{$d['created_by']=$actor;$id=$this->insert('work_order_materials',$d);}foreach($this->materials($wo) as $r)if((int)$r['id']===$id)return$r;throw new NotFoundException('Work order material not found.');}
    public function deleteMaterial(int $wo,int $id,int $actor):void{$this->softDelete('work_order_materials',$id,$actor,['work_order_id'=>$wo]);}
    public function visits(int $id):array{$s=$this->pdo->prepare("SELECT v.*,u.name technician_name FROM field_visits v JOIN technicians t ON t.id=v.technician_id JOIN users u ON u.id=t.user_id WHERE v.work_order_id=? AND v.deleted_at IS NULL ORDER BY v.visit_number");$s->execute([$id]);return$s->fetchAll();}
    public function createVisit(int $wo,array $d,int $actor):array{$d['work_order_id']=$wo;$d['visit_number']=(int)$this->scalar('SELECT COALESCE(MAX(visit_number),0)+1 FROM field_visits WHERE work_order_id=?',[$wo]);$d['created_by']=$actor;$id=$this->insert('field_visits',$d);return$this->row('field_visits',$id,$wo);}
    public function updateVisit(int $wo,int $id,array $d,int $actor):array{$this->update('field_visits',$id,$d+['updated_by'=>$actor],['work_order_id'=>$wo]);return$this->row('field_visits',$id,$wo);}
    public function logs(int $wo):array{$s=$this->pdo->prepare("SELECT l.*,u.name technician_name FROM work_logs l JOIN technicians t ON t.id=l.technician_id JOIN users u ON u.id=t.user_id WHERE l.work_order_id=? AND l.deleted_at IS NULL ORDER BY l.created_at DESC");$s->execute([$wo]);return$s->fetchAll();}
    public function saveLog(int $wo,?int $id,array $d,int $actor):array{if($id){$this->update('work_logs',$id,$d+['updated_by'=>$actor],['work_order_id'=>$wo]);}else{$d['work_order_id']=$wo;$d['created_by']=$actor;$id=$this->insert('work_logs',$d);}return$this->row('work_logs',$id,$wo);}
    public function deleteLog(int $wo,int $id,int $actor):void{$this->softDelete('work_logs',$id,$actor,['work_order_id'=>$wo]);}
    public function timeline(int $id):array{$s=$this->pdo->prepare("SELECT h.*,u.name actor_name FROM work_order_history h LEFT JOIN users u ON u.id=h.actor_user_id WHERE h.work_order_id=? ORDER BY h.created_at DESC");$s->execute([$id]);return$s->fetchAll();}
    public function history(int $id,string $event,int $actor,string $description,?string $old=null,?string $new=null,?array $meta=null):void{$s=$this->pdo->prepare('INSERT INTO work_order_history(work_order_id,event_type,actor_user_id,old_status,new_status,description,metadata) VALUES(?,?,?,?,?,?,?)');$s->execute([$id,$event,$actor,$old,$new,$description,$meta?json_encode($meta,JSON_THROW_ON_ERROR):null]);}

    public function technicianRelation(int $id,string $resource):array{$map=['skills'=>['technician_skills','skill_name'],'service-areas'=>['technician_service_areas','city'],'availability'=>['technician_availability','starts_at']];if(!isset($map[$resource]))throw new NotFoundException('Technician resource not found.');[$table,$sort]=$map[$resource];$s=$this->pdo->prepare("SELECT * FROM {$table} WHERE technician_id=? AND deleted_at IS NULL ORDER BY {$sort}");$s->execute([$id]);return$s->fetchAll();}
    public function saveTechnicianRelation(int $id,string $resource,array $d,int $actor):array{$map=['skills'=>'technician_skills','service-areas'=>'technician_service_areas','availability'=>'technician_availability'];$table=$map[$resource]??throw new NotFoundException('Technician resource not found.');$d['technician_id']=$id;$d['created_by']=$actor;$rowId=$this->insert($table,$d);foreach($this->technicianRelation($id,$resource)as$r)if((int)$r['id']===$rowId)return$r;throw new \RuntimeException('Unable to load technician resource.');}
    public function updateTechnicianRelation(int $id,string $resource,int $rowId,array $d,int $actor):array{$map=['skills'=>'technician_skills','service-areas'=>'technician_service_areas','availability'=>'technician_availability'];$table=$map[$resource]??throw new NotFoundException('Technician resource not found.');$this->update($table,$rowId,$d+['updated_by'=>$actor],['technician_id'=>$id]);foreach($this->technicianRelation($id,$resource)as$r)if((int)$r['id']===$rowId)return$r;throw new NotFoundException('Technician resource not found.');}
    public function deleteTechnicianRelation(int $id,string $resource,int $rowId,int $actor):void{$map=['skills'=>'technician_skills','service-areas'=>'technician_service_areas','availability'=>'technician_availability'];$this->softDelete($map[$resource]??throw new NotFoundException('Technician resource not found.'),$rowId,$actor,['technician_id'=>$id]);}
    public function customerContext(int $customerId):?array{$s=$this->pdo->prepare('SELECT id,full_name,address,city,area FROM customers WHERE id=? AND deleted_at IS NULL');$s->execute([$customerId]);return$s->fetch()?:null;}
    public function lookup(string $r,string $search):array{$like='%'.$search.'%';$map=['customers'=>["SELECT id,customer_code code,full_name name,address,city,area FROM customers WHERE deleted_at IS NULL AND (full_name LIKE ? OR customer_code LIKE ?) ORDER BY full_name LIMIT 30",[$like,$like]],'connections'=>["SELECT id,connection_number code,name,customer_id,status FROM connections WHERE deleted_at IS NULL AND (name LIKE ? OR connection_number LIKE ?) ORDER BY name LIMIT 30",[$like,$like]],'users'=>["SELECT u.id,u.name,u.email FROM users u WHERE u.deleted_at IS NULL AND (u.name LIKE ? OR u.email LIKE ?) ORDER BY u.name LIMIT 30",[$like,$like]],'products'=>["SELECT id,sku code,name,tracking_mode,standard_cost FROM inventory_products WHERE deleted_at IS NULL AND status='active' AND (name LIKE ? OR sku LIKE ?) ORDER BY name LIMIT 30",[$like,$like]],'assets'=>["SELECT a.id,a.product_id,a.asset_tag code,CONCAT(p.name,' / ',a.serial_number) name,a.status FROM inventory_assets a JOIN inventory_products p ON p.id=a.product_id WHERE a.deleted_at IS NULL AND a.status IN ('in_stock','assigned') AND (a.asset_tag LIKE ? OR a.serial_number LIKE ?) LIMIT 30",[$like,$like]],'teams'=>["SELECT id,code,name,status FROM field_teams WHERE deleted_at IS NULL AND name LIKE ? ORDER BY name LIMIT 30",[$like]],'warehouse-locations'=>["SELECT wl.id,wl.code,CONCAT(w.name,' / ',wl.name) name FROM warehouse_locations wl JOIN warehouses w ON w.id=wl.warehouse_id WHERE wl.deleted_at IS NULL AND (wl.name LIKE ? OR wl.code LIKE ?) LIMIT 30",[$like,$like]]];[$sql,$p]=$map[$r]??throw new NotFoundException('Lookup resource not found.');$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetchAll();}
    public function transaction(callable $cb):mixed{if($this->pdo->inTransaction())return$cb();$this->pdo->beginTransaction();try{$v=$cb();$this->pdo->commit();return$v;}catch(\Throwable$e){$this->pdo->rollBack();throw$e;}}

    private function requestSelect():string{return "SELECT ir.*,c.full_name customer_name,c.customer_code,c.phone customer_phone,cn.connection_number,cn.name connection_name,u.name technician_name FROM installation_requests ir JOIN customers c ON c.id=ir.customer_id JOIN connections cn ON cn.id=ir.connection_id LEFT JOIN technicians t ON t.id=ir.assigned_technician_id LEFT JOIN users u ON u.id=t.user_id";}
    private function orderSelect():string{return "SELECT wo.*,c.full_name customer_name,c.customer_code,c.phone customer_phone,cn.connection_number,u.name technician_name,ft.name team_name FROM work_orders wo JOIN customers c ON c.id=wo.customer_id LEFT JOIN connections cn ON cn.id=wo.connection_id LEFT JOIN technicians t ON t.id=wo.assigned_technician_id LEFT JOIN users u ON u.id=t.user_id LEFT JOIN field_teams ft ON ft.id=wo.field_team_id";}
    private function technicianSelect():string{return "SELECT t.*,u.name,u.email,ft.name team_name,(SELECT COUNT(*) FROM work_orders wo WHERE wo.assigned_technician_id=t.id AND wo.status IN ('assigned','scheduled','in_progress') AND wo.deleted_at IS NULL) assigned_work_orders FROM technicians t JOIN users u ON u.id=t.user_id LEFT JOIN field_teams ft ON ft.id=t.field_team_id";}
    private function paged(string $table,string $alias,string $select,FieldServiceListFilters $f,array $filterMap,array $searchCols,array $sortMap):array{$where=["{$alias}.deleted_at IS NULL"];$p=[];foreach($f->filters as$k=>$v){if($v===''||$v===null)continue;if($k==='search'){continue;}if(isset($filterMap[$k])){$expr=$filterMap[$k];$where[]=$expr.(str_contains($expr,' ')?' ?':' = ?');$p[]=$v;}}if(!empty($f->filters['search'])){$where[]='('.implode(' OR ',array_map(fn($c)=>"{$c} LIKE ?",$searchCols)).')';foreach($searchCols as$_)$p[]='%'.$f->filters['search'].'%';}$key=ltrim($f->sort,'-');$sort=$sortMap[$key]??$sortMap['created_at'];$direction=str_starts_with($f->sort,'-')?'DESC':'ASC';$count=$this->pdo->prepare('SELECT COUNT(*) FROM ('.$select.' WHERE '.implode(' AND ',$where).') counted');$count->execute($p);$total=(int)$count->fetchColumn();$offset=($f->page-1)*$f->perPage;$s=$this->pdo->prepare($select.' WHERE '.implode(' AND ',$where)." ORDER BY {$sort} {$direction} LIMIT {$f->perPage} OFFSET {$offset}");$s->execute($p);return['items'=>$s->fetchAll(),'total'=>$total,'page'=>$f->page,'perPage'=>$f->perPage,'lastPage'=>max(1,(int)ceil($total/$f->perPage))];}
    private function insert(string $table,array $d):int{$d=array_filter($d,fn($v)=>$v!==null);$cols=array_keys($d);$s=$this->pdo->prepare("INSERT INTO {$table} (`".implode('`,`',$cols).'`) VALUES ('.implode(',',array_fill(0,count($cols),'?')).')');try{$s->execute(array_values($d));}catch(\PDOException$e){throw new ValidationException([['code'=>'invalid_or_duplicate_reference','detail'=>'A selected reference is invalid or this record already exists.']]);}return(int)$this->pdo->lastInsertId();}
    private function update(string $table,int $id,array $d,array $scope=[]):void{$d=array_filter($d,fn($v)=>$v!==null);if(!$d)return;$set=implode(',',array_map(fn($k)=>"`{$k}`=?",array_keys($d)));$where=['id=?','deleted_at IS NULL'];$p=[...array_values($d),$id];foreach($scope as$k=>$v){$where[]="`{$k}`=?";$p[]=$v;}$s=$this->pdo->prepare("UPDATE {$table} SET {$set} WHERE ".implode(' AND ',$where));$s->execute($p);if(!$s->rowCount()&&!$this->scalar("SELECT 1 FROM {$table} WHERE id=?",[$id]))throw new NotFoundException('Field-service record not found.');}
    private function softDelete(string $t,int $id,int $actor,array $scope=[]):void{$d=['deleted_at'=>gmdate('Y-m-d H:i:s')];if(!in_array($t,['work_order_history'],true))$d['updated_by']=$actor;$this->update($t,$id,$d,$scope);}
    private function row(string $t,int $id,int $wo):array{$s=$this->pdo->prepare("SELECT * FROM {$t} WHERE id=? AND work_order_id=? AND deleted_at IS NULL");$s->execute([$id,$wo]);return$s->fetch()?:throw new NotFoundException('Field-service record not found.');}
    private function scalar(string $q,array $p=[]):mixed{$s=$this->pdo->prepare($q);$s->execute($p);return$s->fetchColumn();}
    private function number(string $prefix):string{return$prefix.'-'.gmdate('Y').'-'.strtoupper(bin2hex(random_bytes(4)));}
}
