export type WorkOrderType='installation'|'maintenance'|'repair'|'equipment_replacement'|'relocation'|'site_survey'|'disconnection';
export type WorkOrderStatus='pending'|'assigned'|'scheduled'|'in_progress'|'on_hold'|'completed'|'failed'|'cancelled';
export type Priority='low'|'normal'|'high'|'urgent';
export interface WorkOrder{id:number;work_order_number:string;installation_request_id:number|null;customer_id:number;customer_name:string;customer_code:string;customer_phone?:string;connection_id:number|null;connection_number?:string|null;assigned_technician_id:number|null;technician_name?:string|null;field_team_id:number|null;team_name?:string|null;type:WorkOrderType;priority:Priority;status:WorkOrderStatus;title:string;service_address:string;scheduled_start_at:string|null;scheduled_end_at:string|null;started_at:string|null;completed_at:string|null;estimated_duration_minutes:number;installation_charge:string;notes:string|null;completion_notes:string|null;materials?:Material[];visits?:FieldVisit[];logs?:WorkLog[];timeline?:TimelineItem[];}
export interface InstallationRequest{id:number;request_number:string;customer_id:number;customer_name:string;customer_code:string;connection_id:number;connection_number:string;assigned_technician_id:number|null;technician_name?:string|null;priority:Priority;status:'pending'|'assigned'|'scheduled'|'in_progress'|'completed'|'cancelled';source:string;service_address:string;preferred_start_at:string|null;preferred_end_at:string|null;scheduled_start_at:string|null;scheduled_end_at:string|null;notes:string|null;created_at:string;}
export interface Technician{id:number;user_id:number;name:string;email:string;field_team_id:number|null;team_name:string|null;employee_code:string;phone:string|null;status:'active'|'inactive'|'on_leave';max_daily_jobs:number;assigned_work_orders:number;skills?:Array<Record<string,unknown>>;service_areas?:Array<Record<string,unknown>>;availability?:Array<Record<string,unknown>>;}
export interface Material{id:number;product_id:number;product_name:string;sku:string;tracking_mode:'quantity'|'serialized';asset_id:number|null;asset_tag:string|null;warehouse_location_id:number|null;quantity_planned:string;quantity_used:string;unit_cost:string;usage_status:string;}
export interface FieldVisit{id:number;visit_number:number;technician_id:number;technician_name:string;status:string;scheduled_start_at:string|null;checked_in_at:string|null;checked_out_at:string|null;before_photo_reference:string|null;after_photo_reference:string|null;customer_signature_reference:string|null;}
export interface WorkLog{id:number;log_type:string;description:string;technician_name:string;started_at:string|null;duration_minutes:number|null;created_at:string;}
export interface TimelineItem{id:number;event_type:string;description:string;actor_name:string|null;old_status:string|null;new_status:string|null;metadata:Record<string,unknown>|null;created_at:string;}
export interface Dashboard{pending_installations:number;todays_work_orders:number;active_technicians:number;completed_jobs:number;average_installation_hours:number;material_usage:Array<{product_name:string;quantity_used:string}>;recent_orders:WorkOrder[];}
export interface ListMeta{current_page:number;per_page:number;total:number;last_page:number} export interface Resource<T>{type:string;id:string;attributes:T} export interface Page<T>{data:Resource<T>[];meta:ListMeta}
export interface WorkOrderFormValues{installation_request_id?:number|null;customer_id:number;connection_id?:number|null;support_ticket_id?:number|null;assigned_technician_id?:number|null;field_team_id?:number|null;type:WorkOrderType;priority:Priority;title:string;service_address:string;scheduled_start_at?:string;scheduled_end_at?:string;estimated_duration_minutes:number;installation_charge:number;notes?:string;}
export interface InstallationFormValues{customer_id:number;connection_id:number;priority:Priority;service_address:string;preferred_start_at?:string;preferred_end_at?:string;notes?:string;source?:string;}
