<?php

declare(strict_types=1);
namespace SkyFi\Vendors\Services;
use SkyFi\Rbac\Contracts\AuditLoggerContract;use SkyFi\Shared\Exceptions\NotFoundException;use SkyFi\Shared\Exceptions\ValidationException;use SkyFi\Vendors\Contracts\SupplierRatingRepositoryContract;use SkyFi\Vendors\Contracts\SupplierRepositoryContract;use SkyFi\Vendors\DomainModels\SupplierRating;use SkyFi\Vendors\DTOs\RatingData;use SkyFi\Vendors\Validators\RatingValidator;
final class SupplierPerformanceService
{
 public function __construct(private readonly SupplierRatingRepositoryContract $repository,private readonly SupplierRepositoryContract $suppliers,private readonly RatingValidator $validator,private readonly AuditLoggerContract $audit){}
 public function performance(int $vendorId):array{$supplier=$this->supplier($vendorId);$data=$supplier->toArray();return $this->repository->performance($vendorId,null,null,(string)$data['currency']);}
 /** @return array<int,SupplierRating> */public function ratings(int $vendorId):array{$this->supplier($vendorId);return $this->repository->list($vendorId);}
 public function create(int $vendorId,RatingData $data,int $actor,?string $ip=null,?string $agent=null):SupplierRating{$this->supplier($vendorId);$this->validator->validate($data);$this->unique($vendorId,$data);$metrics=$this->snapshot($vendorId,$data);$item=$this->repository->create($vendorId,$data,$metrics,$actor);$this->audit->log($actor,'vendors.rating.created','supplier_rating',$item->id(),null,$item->toArray(),$ip,$agent);return $item;}
 public function update(int $vendorId,int $id,RatingData $data,int $actor,?string $ip=null,?string $agent=null):SupplierRating{$old=$this->rating($vendorId,$id);$this->validator->validate($data);$this->unique($vendorId,$data,$id);$metrics=$this->snapshot($vendorId,$data);$item=$this->repository->update($id,$data,$metrics,$actor);$this->audit->log($actor,'vendors.rating.updated','supplier_rating',$id,$old->toArray(),$item->toArray(),$ip,$agent);return $item;}
 public function delete(int $vendorId,int $id,int $actor,?string $ip=null,?string $agent=null):void{$old=$this->rating($vendorId,$id);$this->repository->delete($id,$actor);$this->audit->log($actor,'vendors.rating.archived','supplier_rating',$id,$old->toArray(),null,$ip,$agent);}
 private function snapshot(int $vendorId,RatingData $data):array{$metrics=$this->repository->performance($vendorId,$data->reviewPeriodStart,$data->reviewPeriodEnd,$data->currency);$delivery=(float)$metrics['delivery_performance_pct'];$completion=(float)$metrics['order_completion_pct'];$return=(float)$metrics['return_rate_pct'];$overall=round(($delivery/100*5*.30)+($completion/100*5*.25)+($data->productQualityScore*.30)+((100-$return)/100*5*.15),2);return [...$metrics,'overall_rating'=>min(5,max(0,$overall))];}
 private function supplier(int $id):\SkyFi\Vendors\DomainModels\Supplier{return $this->suppliers->find($id)??throw new NotFoundException('Supplier not found.');}private function rating(int $vendor,int $id):SupplierRating{$item=$this->repository->find($id)??throw new NotFoundException('Supplier rating not found.');if($item->vendorId()!==$vendor)throw new NotFoundException('Supplier rating not found.');return $item;}private function unique(int $vendor,RatingData $data,?int $except=null):void{if($this->repository->periodExists($vendor,$data->reviewPeriodStart,$data->reviewPeriodEnd,$except))throw new ValidationException([['code'=>'duplicate_review_period','detail'=>'A rating already exists for this review period.']]);}
}
