<?php
declare(strict_types=1);
namespace SkyFi\FieldService\Services;
use SkyFi\FieldService\Contracts\FieldServiceRepositoryContract;
use SkyFi\FieldService\Validators\{FieldOperationValidator,FieldServiceValidator};
use SkyFi\Shared\Exceptions\{NotFoundException,ValidationException};
final class FieldOperationService
{
 public function __construct(private readonly FieldServiceRepositoryContract$repo,private readonly FieldOperationValidator$validator,private readonly FieldServiceValidator$fieldValidator){}
 public function materials(int$id):array{return$this->repo->materials($id);} public function saveMaterial(int$wo,?int$id,array$d,int$a):array{$this->fieldValidator->material($d);return$this->repo->saveMaterial($wo,$id,['product_id'=>(int)$d['product_id'],'asset_id'=>isset($d['asset_id'])?(int)$d['asset_id']:null,'warehouse_location_id'=>isset($d['warehouse_location_id'])?(int)$d['warehouse_location_id']:null,'quantity_planned'=>(float)$d['quantity_planned'],'quantity_used'=>(float)$d['quantity_used'],'unit_cost'=>(float)($d['unit_cost']??0),'usage_status'=>$d['usage_status']??'planned','notes'=>trim((string)($d['notes']??''))?:null],$a);}public function deleteMaterial(int$wo,int$id,int$a):void{$this->repo->deleteMaterial($wo,$id,$a);}
 public function visits(int$id):array{return$this->repo->visits($id);} public function createVisit(int$wo,array$d,int$a):array{if((int)($d['technician_id']??0)<1)throw new ValidationException([['code'=>'validation_error','detail'=>'A technician is required.']]);return$this->repo->createVisit($wo,['technician_id'=>(int)$d['technician_id'],'scheduled_start_at'=>$d['scheduled_start_at']??null,'scheduled_end_at'=>$d['scheduled_end_at']??null,'notes'=>$d['notes']??null],$a);} public function visitAction(int$wo,int$id,string$action,array$d,int$a):array{$visit=null;foreach($this->repo->visits($wo)as$v)if((int)$v['id']===$id)$visit=$v;if(!$visit)throw new NotFoundException('Field visit not found.');if($action==='check-in'){$this->validator->checkIn($visit);$changes=['status'=>'checked_in','checked_in_at'=>gmdate('Y-m-d H:i:s'),'check_in_latitude'=>$d['latitude']??null,'check_in_longitude'=>$d['longitude']??null,'gps_accuracy'=>$d['gps_accuracy']??null,'before_photo_reference'=>$d['before_photo_reference']??null];}else{$this->validator->checkOut($visit);$changes=['status'=>'checked_out','checked_out_at'=>gmdate('Y-m-d H:i:s'),'check_out_latitude'=>$d['latitude']??null,'check_out_longitude'=>$d['longitude']??null,'after_photo_reference'=>$d['after_photo_reference']??null,'customer_signature_reference'=>$d['customer_signature_reference']??null,'customer_name'=>$d['customer_name']??null,'notes'=>$d['notes']??null];}return$this->repo->updateVisit($wo,$id,$changes,$a);}
 public function logs(int$id):array{return$this->repo->logs($id);} public function saveLog(int$wo,?int$id,array$d,int$a):array{if(!in_array($d['log_type']??'', ['travel','diagnostic','installation','repair','maintenance','note'],true)||trim((string)($d['description']??''))==='')throw new ValidationException([['code'=>'validation_error','detail'=>'A valid log type and description are required.']]);return$this->repo->saveLog($wo,$id,['field_visit_id'=>isset($d['field_visit_id'])?(int)$d['field_visit_id']:null,'technician_id'=>(int)($d['technician_id']??0),'log_type'=>$d['log_type'],'started_at'=>$d['started_at']??null,'ended_at'=>$d['ended_at']??null,'duration_minutes'=>isset($d['duration_minutes'])?(int)$d['duration_minutes']:null,'description'=>trim($d['description'])],$a);}public function deleteLog(int$wo,int$id,int$a):void{$this->repo->deleteLog($wo,$id,$a);}
}
