<?php
declare(strict_types=1);
namespace SkyFi\FieldService\Services;
use SkyFi\Connections\Services\ConnectionService;
use SkyFi\Customers\Services\CustomerService;
use SkyFi\Billing\Contracts\BillingScheduleRepositoryContract;
use SkyFi\FieldService\Contracts\{FieldServiceRepositoryContract,FieldServiceServiceContract};
use SkyFi\FieldService\DTOs\{FieldServiceListFilters,WorkOrderData};
use SkyFi\FieldService\Validators\{FieldOperationValidator,FieldServiceValidator};
use SkyFi\Inventory\DTOs\StockOperationData;
use SkyFi\Inventory\Services\StockService;
use SkyFi\Rbac\Contracts\AuditLoggerContract;
use SkyFi\Shared\Events\EventDispatcher;
use SkyFi\Shared\Exceptions\{NotFoundException,ValidationException};
final class WorkOrderService implements FieldServiceServiceContract
{
 public function __construct(private readonly FieldServiceRepositoryContract$repo,private readonly FieldServiceValidator$validator,private readonly FieldOperationValidator$operations,private readonly StockService$stock,private readonly ConnectionService$connections,private readonly CustomerService$customers,private readonly BillingScheduleRepositoryContract$billingSchedules,private readonly AuditLoggerContract$audit){}
 public function dashboard():array{return$this->repo->dashboard();} public function list(FieldServiceListFilters$f):array{return$this->repo->listOrders($f);} public function get(int$id):array{$o=$this->repo->findOrder($id)??throw new NotFoundException('Work order not found.');$o['materials']=$this->repo->materials($id);$o['visits']=$this->repo->visits($id);$o['logs']=$this->repo->logs($id);$o['timeline']=$this->repo->timeline($id);return$o;}
 public function create(WorkOrderData$d,int$a):array{$this->validator->order($d);$values=$d->values;$values['status']=($values['assigned_technician_id']??null)?(($values['scheduled_start_at']??null)?'scheduled':'assigned'):'pending';if(($values['assigned_technician_id']??null)&&($values['scheduled_start_at']??null)){if($this->repo->hasScheduleConflict((int)$values['assigned_technician_id'],$values['scheduled_start_at'],$values['scheduled_end_at']))throw new ValidationException([['code'=>'schedule_conflict','detail'=>'The technician already has work scheduled during this period.']]);}$r=$this->repo->createOrder($values,$a);if($r['status']==='scheduled'&&$r['assigned_technician_id']){$this->repo->createVisit((int)$r['id'],['technician_id'=>(int)$r['assigned_technician_id'],'scheduled_start_at'=>$r['scheduled_start_at'],'scheduled_end_at'=>$r['scheduled_end_at'],'notes'=>'Initial scheduled field visit.'],$a);}$this->repo->history((int)$r['id'],'created',$a,'Work order created.',null,$r['status']);$this->audit->log($a,'field.work_order.created','work_order',(int)$r['id'],null,$r);return$r;}
 public function createFromRequest(array$request,int$a):array{if(!empty($request['work_order_id']))throw new ValidationException([['code'=>'work_order_exists','detail'=>'The installation request already has a work order.']]);return$this->create(WorkOrderData::fromArray(['installation_request_id'=>$request['id'],'customer_id'=>$request['customer_id'],'connection_id'=>$request['connection_id'],'assigned_technician_id'=>$request['assigned_technician_id'],'type'=>'installation','priority'=>$request['priority'],'title'=>'Customer installation - '.$request['customer_name'],'service_address'=>$request['service_address'],'scheduled_start_at'=>$request['scheduled_start_at'],'scheduled_end_at'=>$request['scheduled_end_at'],'notes'=>$request['notes']]),$a);}
 public function update(int$id,WorkOrderData$d,int$a):array{$this->validator->order($d);$old=$this->get($id);if(in_array($old['status'],['completed','cancelled'],true))throw new ValidationException([['code'=>'terminal_order','detail'=>'Completed or cancelled work orders cannot be edited.']]);$r=$this->repo->updateOrder($id,$d->values,$a);$this->repo->history($id,'updated',$a,'Work order details updated.');$this->audit->log($a,'field.work_order.updated','work_order',$id,$old,$r);return$r;}
 public function transition(int$id,string$status,array$data,int$a):array{$old=$this->repo->findOrder($id)??throw new NotFoundException('Work order not found.');if($status==='completed')return$this->complete($id,$data,$a);$this->validator->transition($old['status'],$status);$changes=['status'=>$status];if($status==='in_progress')$changes['started_at']=gmdate('Y-m-d H:i:s');if($status==='cancelled'){if(trim((string)($data['reason']??''))==='')throw new ValidationException([['code'=>'reason_required','detail'=>'A cancellation reason is required.']]);$changes['cancellation_reason']=$data['reason'];}if($status==='failed')$changes['failure_reason']=$data['reason']??'Field operation failed.';$r=$this->repo->updateOrder($id,$changes,$a);$this->repo->history($id,'status_changed',$a,'Status changed from '.$old['status'].' to '.$status.'.',$old['status'],$status);$this->audit->log($a,'field.work_order.status_changed','work_order',$id,['status'=>$old['status']],['status'=>$status]);return$r;}
 public function assign(int$id,array$d,int$a):array{$old=$this->repo->findOrder($id)??throw new NotFoundException('Work order not found.');$tech=(int)($d['technician_id']??0);if($tech<1)throw new ValidationException([['code'=>'validation_error','detail'=>'A technician is required.']]);$r=$this->repo->updateOrder($id,['assigned_technician_id'=>$tech,'field_team_id'=>isset($d['team_id'])?(int)$d['team_id']:null,'status'=>($old['scheduled_start_at']??null)?'scheduled':'assigned'],$a);$this->repo->history($id,'assigned',$a,'Work order assigned to a technician.',null,$r['status'],['technician_id'=>$tech]);return$r;}
 public function schedule(int$id,array$d,int$a):array{$old=$this->repo->findOrder($id)??throw new NotFoundException('Work order not found.');$tech=(int)($d['technician_id']??$old['assigned_technician_id']??0);$start=$d['scheduled_start_at']??null;$end=$d['scheduled_end_at']??null;$this->validator->schedule($tech,$start,$end);if($this->repo->hasScheduleConflict($tech,$start,$end,$id))throw new ValidationException([['code'=>'schedule_conflict','detail'=>'The technician already has work scheduled during this period.']]);$r=$this->repo->updateOrder($id,['assigned_technician_id'=>$tech,'scheduled_start_at'=>$start,'scheduled_end_at'=>$end,'status'=>'scheduled'],$a);$visits=$this->repo->visits($id);if($visits===[]){$this->repo->createVisit($id,['technician_id'=>$tech,'scheduled_start_at'=>$start,'scheduled_end_at'=>$end,'notes'=>'Scheduled field visit.'],$a);}else{$latest=end($visits);if(in_array($latest['status'],['scheduled','cancelled'],true)){$this->repo->updateVisit($id,(int)$latest['id'],['technician_id'=>$tech,'scheduled_start_at'=>$start,'scheduled_end_at'=>$end,'status'=>'scheduled'],$a);}else{$this->repo->createVisit($id,['technician_id'=>$tech,'scheduled_start_at'=>$start,'scheduled_end_at'=>$end,'notes'=>'Rescheduled follow-up field visit.'],$a);}}$this->repo->history($id,'scheduled',$a,'Work order scheduled.', $old['status'],'scheduled',['start'=>$start,'end'=>$end]);return$r;}
 public function complete(int$id,array$data,int$a):array{$order=$this->repo->findOrder($id)??throw new NotFoundException('Work order not found.');if($order['status']==='completed')return$order;$materials=$this->repo->materials($id);$visits=$this->repo->visits($id);$this->operations->completion($order,$materials,$visits);$lines=[];foreach($materials as$m){if((float)$m['quantity_used']<=0||$m['usage_status']==='used')continue;$line=['product_id'=>(int)$m['product_id'],'quantity'=>(float)$m['quantity_used'],'source_location_id'=>$m['warehouse_location_id'],'unit_cost'=>(float)$m['unit_cost']];if($m['asset_id']){$line['asset_ids']=[(int)$m['asset_id']];$line['quantity']=1;$line['assignment']=['assignment_type'=>'customer','customer_id'=>(int)$order['customer_id']];}$lines[]=$line;} $movementId=null;if($lines){$movement=$this->stock->post(new StockOperationData('stock_out',$lines,'field_work_order',$order['work_order_number'],isset($order['support_ticket_id'])?(int)$order['support_ticket_id']:null,null,'Field-service material consumption',$data['completion_notes']??null,gmdate('Y-m-d H:i:s')),$a);$movementId=$movement->id();foreach($materials as$m)if((float)$m['quantity_used']>0&&$m['usage_status']!=='used')$this->repo->saveMaterial($id,(int)$m['id'],['usage_status'=>'used','stock_movement_id'=>$movementId],$a);} $r=$this->repo->updateOrder($id,['status'=>'completed','completed_at'=>gmdate('Y-m-d H:i:s'),'completion_notes'=>trim((string)($data['completion_notes']??''))?:'Field work completed.','installation_charge_status'=>(float)$order['installation_charge']>0?'handed_off':'not_applicable'],$a);if($order['installation_request_id'])$this->repo->updateRequest((int)$order['installation_request_id'],['status'=>'completed','completed_at'=>gmdate('Y-m-d H:i:s')],$a);if($order['type']==='installation'&&$order['connection_id']){$connectionId=(int)$order['connection_id'];$this->connections->changeStatus($connectionId,'active',$a,null,null);$customer=$this->customers->get((int)$order['customer_id']);if($customer->status!=='active')$this->customers->changeStatus((int)$order['customer_id'],'active',$a,null,null);if($this->billingSchedules->findByConnection($connectionId)===null){$anchor=gmdate('Y-m-d');$this->billingSchedules->create(['connection_id'=>$connectionId,'billing_cycle'=>'monthly','custom_interval_days'=>null,'anchor_date'=>$anchor,'next_bill_date'=>gmdate('Y-m-d',strtotime('+1 month')),'grace_period_days'=>0,'auto_generate'=>1,'proration_enabled'=>1]);}}$this->repo->history($id,'completed',$a,'Work order completed and integration handoffs processed.',$order['status'],'completed',['stock_movement_id'=>$movementId]);$this->audit->log($a,'field.work_order.completed','work_order',$id,$order,$r);EventDispatcher::dispatch('field.work_order.completed',$r+['stock_movement_id'=>$movementId]);return$r;}
 public function delete(int$id,int$a):void{$o=$this->repo->findOrder($id)??throw new NotFoundException('Work order not found.');if(!in_array($o['status'],['pending','cancelled'],true))throw new ValidationException([['code'=>'invalid_delete','detail'=>'Only pending or cancelled work orders can be deleted.']]);$this->repo->deleteOrder($id,$a);$this->audit->log($a,'field.work_order.deleted','work_order',$id,$o,null);}
}
