<?php

declare(strict_types=1);
namespace SkyFi\Vendors\Repositories;

use PDO;
use SkyFi\Vendors\Contracts\SupplierRatingRepositoryContract;
use SkyFi\Vendors\DomainModels\SupplierRating;
use SkyFi\Vendors\DTOs\RatingData;

final class PdoSupplierRatingRepository implements SupplierRatingRepositoryContract
{
    public function __construct(private readonly PDO $pdo) {}
    public function list(int $vendorId):array{$statement=$this->pdo->prepare('SELECT sr.*,u.name AS rated_by_name FROM supplier_ratings sr LEFT JOIN users u ON u.id=sr.rated_by_user_id WHERE sr.vendor_id=? AND sr.deleted_at IS NULL ORDER BY sr.review_period_end DESC,sr.id DESC');$statement->execute([$vendorId]);return array_map(static fn(array $row):SupplierRating=>SupplierRating::fromRow($row),$statement->fetchAll(PDO::FETCH_ASSOC));}
    public function find(int $id):?SupplierRating{$statement=$this->pdo->prepare('SELECT sr.*,u.name AS rated_by_name,v.name AS supplier_name FROM supplier_ratings sr JOIN vendors v ON v.id=sr.vendor_id LEFT JOIN users u ON u.id=sr.rated_by_user_id WHERE sr.id=? AND sr.deleted_at IS NULL');$statement->execute([$id]);$row=$statement->fetch(PDO::FETCH_ASSOC);return $row?SupplierRating::fromRow($row):null;}
    public function create(int $vendorId,RatingData $data,array $metrics,int $actorId):SupplierRating{$this->pdo->prepare('INSERT INTO supplier_ratings (vendor_id,review_period_start,review_period_end,delivery_performance_pct,order_completion_pct,product_quality_score,return_rate_pct,average_lead_time_days,procurement_value,currency,overall_rating,notes,rated_by_user_id,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$vendorId,$data->reviewPeriodStart,$data->reviewPeriodEnd,$metrics['delivery_performance_pct'],$metrics['order_completion_pct'],$data->productQualityScore,$metrics['return_rate_pct'],$metrics['average_lead_time_days'],$metrics['procurement_value'],$data->currency,$metrics['overall_rating'],$data->notes,$actorId,$actorId,$actorId]);return $this->find((int)$this->pdo->lastInsertId())??throw new \RuntimeException('Rating could not be loaded.');}
    public function update(int $id,RatingData $data,array $metrics,int $actorId):SupplierRating{$this->pdo->prepare('UPDATE supplier_ratings SET review_period_start=?,review_period_end=?,delivery_performance_pct=?,order_completion_pct=?,product_quality_score=?,return_rate_pct=?,average_lead_time_days=?,procurement_value=?,currency=?,overall_rating=?,notes=?,rated_by_user_id=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NULL')->execute([$data->reviewPeriodStart,$data->reviewPeriodEnd,$metrics['delivery_performance_pct'],$metrics['order_completion_pct'],$data->productQualityScore,$metrics['return_rate_pct'],$metrics['average_lead_time_days'],$metrics['procurement_value'],$data->currency,$metrics['overall_rating'],$data->notes,$actorId,$actorId,$id]);return $this->find($id)??throw new \RuntimeException('Rating could not be loaded.');}
    public function delete(int $id,int $actorId):void{$this->pdo->prepare('UPDATE supplier_ratings SET deleted_at=CURRENT_TIMESTAMP,updated_by=? WHERE id=?')->execute([$actorId,$id]);}
    public function periodExists(int $vendorId,string $start,string $end,?int $exceptId=null):bool{$sql='SELECT COUNT(*) FROM supplier_ratings WHERE vendor_id=? AND review_period_start=? AND review_period_end=? AND deleted_at IS NULL'.($exceptId!==null?' AND id<>?':'');$params=[$vendorId,$start,$end];if($exceptId!==null)$params[]=$exceptId;$statement=$this->pdo->prepare($sql);$statement->execute($params);return (int)$statement->fetchColumn()>0;}
    public function performance(int $vendorId,?string $start=null,?string $end=null,?string $currency=null):array
    {
        $currency=$currency?:$this->supplierCurrency($vendorId);$dateSql='';$params=['vendor'=>$vendorId,'currency'=>$currency];
        if($start!==null){$dateSql.=' AND po.order_date>=:start';$params['start']=$start;}if($end!==null){$dateSql.=' AND po.order_date<=:end';$params['end']=$end;}
        $orderSql="SELECT COUNT(*) AS eligible_orders,SUM(CASE WHEN x.status IN ('fully_received','closed') THEN 1 ELSE 0 END) AS completed_orders,SUM(CASE WHEN x.first_receipt IS NOT NULL AND x.expected_delivery_date IS NOT NULL AND DATE(x.first_receipt)<=x.expected_delivery_date THEN 1 ELSE 0 END) AS on_time_orders,SUM(CASE WHEN x.first_receipt IS NOT NULL AND x.expected_delivery_date IS NOT NULL THEN 1 ELSE 0 END) AS measured_deliveries,AVG(CASE WHEN x.first_receipt IS NOT NULL THEN DATEDIFF(DATE(x.first_receipt),x.order_date) END) AS average_lead_time_days,COALESCE(SUM(x.total_amount),0) AS procurement_value FROM (SELECT po.id,po.status,po.order_date,po.expected_delivery_date,po.total_amount,MIN(gr.received_at) AS first_receipt FROM purchase_orders po LEFT JOIN goods_receipts gr ON gr.purchase_order_id=po.id AND gr.deleted_at IS NULL WHERE po.vendor_id=:vendor AND po.currency=:currency AND po.deleted_at IS NULL AND po.status NOT IN ('draft','rejected','cancelled'){$dateSql} GROUP BY po.id) x";
        $statement=$this->pdo->prepare($orderSql);$statement->execute($params);$order=$statement->fetch(PDO::FETCH_ASSOC)?:[];
        $returnSql="SELECT COALESCE(SUM(poi.quantity_received),0) AS received,COALESCE(SUM(poi.quantity_returned+poi.quantity_damaged),0) AS returned FROM purchase_order_items poi JOIN purchase_orders po ON po.id=poi.purchase_order_id WHERE po.vendor_id=:vendor AND po.currency=:currency AND po.deleted_at IS NULL AND po.status NOT IN ('draft','rejected','cancelled'){$dateSql}";$statement=$this->pdo->prepare($returnSql);$statement->execute($params);$returns=$statement->fetch(PDO::FETCH_ASSOC)?:[];
        $eligible=(int)($order['eligible_orders']??0);$completed=(int)($order['completed_orders']??0);$measured=(int)($order['measured_deliveries']??0);$onTime=(int)($order['on_time_orders']??0);$received=(float)($returns['received']??0);$returned=(float)($returns['returned']??0);
        $delivery=$measured>0?round($onTime/$measured*100,2):0.0;$completion=$eligible>0?round($completed/$eligible*100,2):0.0;$returnRate=$received>0?round(min(100,$returned/$received*100),2):0.0;
        $qualityStatement=$this->pdo->prepare('SELECT product_quality_score,overall_rating FROM supplier_ratings WHERE vendor_id=? AND deleted_at IS NULL ORDER BY review_period_end DESC,id DESC LIMIT 1');$qualityStatement->execute([$vendorId]);$latest=$qualityStatement->fetch(PDO::FETCH_ASSOC)?:[];
        return ['eligible_orders'=>$eligible,'completed_orders'=>$completed,'measured_deliveries'=>$measured,'on_time_orders'=>$onTime,'delivery_performance_pct'=>$delivery,'order_completion_pct'=>$completion,'product_quality_score'=>isset($latest['product_quality_score'])?(float)$latest['product_quality_score']:null,'return_rate_pct'=>$returnRate,'average_lead_time_days'=>round((float)($order['average_lead_time_days']??0),2),'procurement_value'=>(float)($order['procurement_value']??0),'currency'=>$currency,'overall_rating'=>isset($latest['overall_rating'])?(float)$latest['overall_rating']:null];
    }
    private function supplierCurrency(int $vendorId):string{$statement=$this->pdo->prepare('SELECT currency FROM vendors WHERE id=?');$statement->execute([$vendorId]);return (string)($statement->fetchColumn()?:'PKR');}
}
