export type PackageStatus = 'draft' | 'active' | 'inactive' | 'archived';
export type PackageCategory = 'residential' | 'business' | 'corporate' | 'enterprise' | 'dedicated' | 'custom';
export interface PackagePricing { monthly:number; quarterly:number; semi_annual:number; annual:number; installation_charge:number; supports_tax:boolean; supports_discount:boolean }
export interface PackageBandwidth { download_kbps:number; upload_kbps:number; burst_download_kbps:number|null; burst_upload_kbps:number|null; cir_kbps:number|null; mir_kbps:number|null; data_limit_bytes:number|null; is_unlimited:boolean }
export interface InternetPackage { id:number; name:string; code:string; description:string|null; category:PackageCategory; category_name:string; status:PackageStatus; pricing:PackagePricing; bandwidth:PackageBandwidth; network:Record<string,string|number|null>; customer_rules:Record<string,string|number|boolean|null>; billing:Record<string,string|boolean>; technical:Record<string,string|null>; monthly_price?:string; download_kbps?:number; upload_kbps?:number; is_unlimited?:boolean; created_at:string; updated_at:string }
export interface PackageFormData { name:string; code:string; description:string; category:PackageCategory; status:PackageStatus; pricing:PackagePricing; bandwidth:PackageBandwidth; network:{pppoe_profile_name:string;hotspot_profile_name:string;queue_type:string;vlan_id:number|null;ip_pool:string;dns_profile:string}; customer_rules:{max_devices:number|null;allows_static_ip:boolean;allows_public_ip:boolean;allows_dynamic_ip:boolean;suspension_policy:string;grace_period_days:number}; billing:{default_billing_cycle:string;auto_renew:boolean;invoice_generation_mode:string;supports_late_fee:boolean}; technical:{radius_profile:string;authentication_method:string;qos_profile:string} }
export interface PackageFilters { search?:string;status?:string;category?:string;billing_cycle?:string;unlimited?:string }
export interface PackageListResponse { data:Array<{type:'packages';id:string;attributes:InternetPackage}>;meta:{current_page:number;per_page:number;total:number;last_page:number} }
export interface PackageStatisticsData {total:number;active:number;draft:number;inactive:number;by_category:Array<{code:string;name:string;count:number}>}
