<?php

declare(strict_types=1);
namespace SkyFi\Payments\Repositories;
use PDO;
use SkyFi\Payments\Contracts\PaymentRepositoryContract;
use SkyFi\Payments\DTOs\PaymentListFilters;
use SkyFi\Payments\Models\Payment;
final class PdoPaymentRepository implements PaymentRepositoryContract
{
 public function __construct(private readonly PDO $pdo){}
 public function transaction(callable $callback):mixed{$own=!$this->pdo->inTransaction();if($own)$this->pdo->beginTransaction();try{$r=$callback();if($own)$this->pdo->commit();return $r;}catch(\Throwable $e){if($own&&$this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 public function list(PaymentListFilters $f):array
 {
  [$where,$params,$joins]=$this->where($f);$count=$this->pdo->prepare("SELECT COUNT(DISTINCT p.id) FROM payments p $joins WHERE ".implode(' AND ',$where));$count->execute($params);$total=(int)$count->fetchColumn();
  $allowed=['payment_date','amount','created_at','updated_at','status','payment_number'];$raw=ltrim($f->sort,'-');$col=in_array($raw,$allowed,true)?'p.'.$raw:'p.payment_date';$dir=str_starts_with($f->sort,'-')?'DESC':'ASC';$offset=($f->page-1)*$f->perPage;
  $sql="SELECT DISTINCT ".$this->select()." FROM payments p $joins WHERE ".implode(' AND ',$where)." ORDER BY $col $dir LIMIT :limit OFFSET :offset";$st=$this->pdo->prepare($sql);foreach($params as $k=>$v)$st->bindValue($k,$v);$st->bindValue('limit',$f->perPage,PDO::PARAM_INT);$st->bindValue('offset',$offset,PDO::PARAM_INT);$st->execute();$items=[];while($r=$st->fetch())$items[]=Payment::fromRow($r);return ['items'=>$items,'total'=>$total,'page'=>$f->page,'perPage'=>$f->perPage,'lastPage'=>max(1,(int)ceil($total/$f->perPage))];
 }
 public function find(int $id,bool $lock=false):?Payment
 {
  $st=$this->pdo->prepare('SELECT '.$this->select().' FROM payments p LEFT JOIN customers c ON c.id=p.customer_id LEFT JOIN connections cn ON cn.id=p.connection_id LEFT JOIN payment_methods pm ON pm.id=p.payment_method_id LEFT JOIN payment_accounts pa ON pa.id=p.payment_account_id LEFT JOIN users u ON u.id=p.collected_by LEFT JOIN receipts r ON r.payment_id=p.id AND r.deleted_at IS NULL WHERE p.id=:id AND p.deleted_at IS NULL'.($lock?' FOR UPDATE':''));$st->execute(['id'=>$id]);$row=$st->fetch();if(!$row)return null;
  $row['allocations']=$this->all('SELECT a.*,i.invoice_number FROM payment_allocations a LEFT JOIN invoices i ON i.id=a.invoice_id WHERE a.payment_id=? ORDER BY a.created_at DESC',[$id]);$row['refunds']=$this->all('SELECT pr.*,u.name AS refunded_by_name FROM payment_refunds pr LEFT JOIN users u ON u.id=pr.refunded_by WHERE pr.payment_id=? AND pr.deleted_at IS NULL ORDER BY pr.created_at DESC',[$id]);$row['activities']=$this->all('SELECT a.*,u.name AS performed_by_name FROM payment_activities a LEFT JOIN users u ON u.id=a.performed_by WHERE a.payment_id=? ORDER BY a.created_at DESC',[$id]);$row['attachments']=$this->all('SELECT id,original_name,mime_type,storage_key,created_at FROM payment_attachments WHERE payment_id=?',[$id]);return Payment::fromRow($row);
 }
 public function create(array $d):Payment{$cols=array_keys($d);$st=$this->pdo->prepare('INSERT INTO payments('.implode(',',$cols).') VALUES(:'.implode(',:',$cols).')');$st->execute($d);return $this->find((int)$this->pdo->lastInsertId())??throw new \RuntimeException('Payment could not be retrieved.');}
 public function update(int $id,array $d):Payment{$set=implode(',',array_map(fn($k)=>"$k=:$k",array_keys($d)));$this->pdo->prepare("UPDATE payments SET $set WHERE id=:id AND deleted_at IS NULL")->execute([...$d,'id'=>$id]);return $this->find($id)??throw new \RuntimeException('Payment could not be retrieved.');}
 public function softDelete(int $id):void{$this->pdo->prepare('UPDATE payments SET deleted_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$id]);}
 public function numberExists(string $n):bool{$s=$this->pdo->prepare('SELECT 1 FROM payments WHERE payment_number=? UNION SELECT 1 FROM receipts WHERE receipt_number=?');$s->execute([$n,$n]);return(bool)$s->fetchColumn();}
 public function referenceExists(string $r,?int $x=null):bool{$sql='SELECT 1 FROM payments WHERE reference_number=? AND deleted_at IS NULL';$p=[$r];if($x){$sql.=' AND id<>?';$p[]=$x;}$s=$this->pdo->prepare($sql);$s->execute($p);return(bool)$s->fetchColumn();}
 public function customerExists(int $id):bool{$s=$this->pdo->prepare('SELECT 1 FROM customers WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);return(bool)$s->fetchColumn();}
 public function connectionBelongsTo(int $id,int $c):bool{$s=$this->pdo->prepare('SELECT 1 FROM connections WHERE id=? AND customer_id=? AND deleted_at IS NULL');$s->execute([$id,$c]);return(bool)$s->fetchColumn();}
 public function methodAndAccount(int $m,int $a):?array{$s=$this->pdo->prepare('SELECT pm.code,pm.name,pm.requires_reference,pm.is_active,pm.is_future,pa.id account_id,pa.name account_name FROM payment_methods pm JOIN payment_accounts pa ON pa.id=? AND pa.deleted_at IS NULL WHERE pm.id=? AND (pa.payment_method_id IS NULL OR pa.payment_method_id=pm.id) AND pa.is_active=1');$s->execute([$a,$m]);return$s->fetch()?:null;}
 public function lookups():array{return ['methods'=>$this->all('SELECT * FROM payment_methods ORDER BY is_future,name'),'accounts'=>$this->all('SELECT pa.*,pm.code AS payment_method_code FROM payment_accounts pa LEFT JOIN payment_methods pm ON pm.id=pa.payment_method_id WHERE pa.deleted_at IS NULL ORDER BY pa.name')];}
 public function invoiceForAllocation(int $id,int $customer,bool $lock=true):?array{$s=$this->pdo->prepare('SELECT * FROM invoices WHERE id=? AND customer_id=? AND deleted_at IS NULL'.($lock?' FOR UPDATE':''));$s->execute([$id,$customer]);return$s->fetch()?:null;}
 public function addAllocation(int $pid,array $d):int{$s=$this->pdo->prepare('INSERT INTO payment_allocations(payment_id,invoice_id,allocation_type,amount,allocated_at,allocated_by,notes) VALUES(:payment_id,:invoice_id,:allocation_type,:amount,:allocated_at,:allocated_by,:notes)');$s->execute(['payment_id'=>$pid,...$d]);return(int)$this->pdo->lastInsertId();}
 public function reverseAllocations(int $pid,int $u):array{$rows=$this->all('SELECT * FROM payment_allocations WHERE payment_id=? AND reversed_at IS NULL FOR UPDATE',[$pid]);$this->pdo->prepare('UPDATE payment_allocations SET reversed_at=NOW(),reversed_by=? WHERE payment_id=? AND reversed_at IS NULL')->execute([$u,$pid]);$customer=$this->pdo->prepare('SELECT customer_id FROM payments WHERE id=?');$customer->execute([$pid]);$customerId=(int)$customer->fetchColumn();foreach($rows as $row)if($row['allocation_type']!=='invoice')$this->addCredit($customerId,$pid,(int)$row['id'],'reversal',number_format(-(float)$row['amount'],2,'.',''),$u,'Customer balance reversed with payment.');return$rows;}
 public function refundAllocations(int $pid,string $amount,int $u):array
 {
  $remaining=(float)$amount;$affected=[];$rows=$this->all("SELECT * FROM payment_allocations WHERE payment_id=? AND reversed_at IS NULL ORDER BY (allocation_type='invoice') DESC,id DESC FOR UPDATE",[$pid]);
  foreach($rows as $row){if($remaining<=0)break;$take=min($remaining,(float)$row['amount']);$this->pdo->prepare('UPDATE payment_allocations SET reversed_at=NOW(),reversed_by=? WHERE id=?')->execute([$u,$row['id']]);if((float)$row['amount']>$take){$this->addAllocation($pid,['invoice_id'=>$row['invoice_id'],'allocation_type'=>$row['allocation_type'],'amount'=>number_format((float)$row['amount']-$take,2,'.',''),'allocated_at'=>date('Y-m-d H:i:s'),'allocated_by'=>$u,'notes'=>'Remaining allocation after partial refund.']);}if($row['allocation_type']!=='invoice'){$customer=$this->pdo->prepare('SELECT customer_id FROM payments WHERE id=?');$customer->execute([$pid]);$this->addCredit((int)$customer->fetchColumn(),$pid,(int)$row['id'],'refund',number_format(-$take,2,'.',''),$u,'Customer balance reduced by payment refund.');}$remaining-=$take;if($row['invoice_id'])$affected[]=(int)$row['invoice_id'];}
  return array_values(array_unique($affected));
 }
 public function recalculateInvoice(int $id,int $u,string $description):void
 {
  $s=$this->pdo->prepare('SELECT total_amount,due_date FROM invoices WHERE id=? AND deleted_at IS NULL FOR UPDATE');$s->execute([$id]);$r=$s->fetch();if(!$r)return;$sum=$this->pdo->prepare("SELECT COALESCE(SUM(pa.amount),0) FROM payment_allocations pa JOIN payments p ON p.id=pa.payment_id AND p.deleted_at IS NULL WHERE pa.invoice_id=? AND pa.allocation_type='invoice' AND pa.reversed_at IS NULL AND p.status NOT IN ('cancelled','failed','refunded')");$sum->execute([$id]);$r['applied']=$sum->fetchColumn();$balance=max(0,(float)$r['total_amount']-(float)$r['applied']);$status=$balance<=0?'paid':($r['due_date']<date('Y-m-d')?'overdue':((float)$r['applied']>0?'partially_paid':'issued'));$this->pdo->prepare('UPDATE invoices SET balance_due=?,status=?,updated_by=? WHERE id=?')->execute([number_format($balance,2,'.',''),$status,$u,$id]);$this->pdo->prepare('INSERT INTO invoice_activities(invoice_id,action,description,performed_by) VALUES(?,?,?,?)')->execute([$id,'payment_recalculated',$description,$u]);
 }
 public function addReceipt(int $pid,string $n,int $u,array $snap):void{$this->pdo->prepare('INSERT INTO receipts(payment_id,receipt_number,issued_at,issued_by,snapshot) VALUES(?,?,NOW(),?,?)')->execute([$pid,$n,$u,json_encode($snap,JSON_THROW_ON_ERROR)]);}
 public function addActivity(int $pid,string $a,string $d,int $u,?array $m=null):void{$this->pdo->prepare('INSERT INTO payment_activities(payment_id,action,description,metadata,performed_by) VALUES(?,?,?,?,?)')->execute([$pid,$a,$d,$m?json_encode($m,JSON_THROW_ON_ERROR):null,$u]);}
 public function addCredit(int $c,int $p,int $a,string $t,string $amount,int $u,string $d):void{$this->pdo->prepare('INSERT INTO customer_credit_ledger(customer_id,payment_id,allocation_id,entry_type,amount,description,effective_at,created_by) VALUES(?,?,?,?,?,?,NOW(),?)')->execute([$c,$p,$a,$t,$amount,$d,$u]);}
 public function addRefund(int $p,string $n,string $amount,string $reason,?string $notes,?string $ref,int $u):int{$this->pdo->prepare('INSERT INTO payment_refunds(refund_number,payment_id,amount,status,reason,notes,reference_number,refunded_at,refunded_by) VALUES(?,?,?,\'completed\',?,?,?,NOW(),?)')->execute([$n,$p,$amount,$reason,$notes,$ref,$u]);return(int)$this->pdo->lastInsertId();}
 public function addFinancialEvent(int $p,?int $r,string $t,string $amount,array $payload,string $key):void{$this->pdo->prepare('INSERT INTO payment_financial_events(payment_id,refund_id,event_type,amount,payload,idempotency_key,occurred_at) VALUES(?,?,?,?,?,?,NOW())')->execute([$p,$r,$t,$amount,json_encode($payload,JSON_THROW_ON_ERROR),$key]);}
 public function statistics():array
 {
  $r=$this->pdo->query("SELECT COALESCE(SUM(CASE WHEN status IN ('completed','partially_applied') AND DATE(payment_date)=CURDATE() THEN amount-refunded_amount ELSE 0 END),0) today_collections,COALESCE(SUM(CASE WHEN status IN ('completed','partially_applied') AND payment_date>=DATE_FORMAT(CURDATE(),'%Y-%m-01') THEN amount-refunded_amount ELSE 0 END),0) monthly_collections,SUM(status='pending') pending_payments,COUNT(*) total_payments FROM payments WHERE deleted_at IS NULL")->fetch();$r['outstanding_balance']=$this->pdo->query("SELECT COALESCE(SUM(balance_due),0) FROM invoices WHERE deleted_at IS NULL AND status IN ('issued','partially_paid','overdue')")->fetchColumn();$r['recent_receipts']=$this->all('SELECT r.receipt_number,r.issued_at,p.id payment_id,p.payment_number,p.amount,c.full_name customer_name FROM receipts r JOIN payments p ON p.id=r.payment_id JOIN customers c ON c.id=p.customer_id WHERE r.deleted_at IS NULL ORDER BY r.issued_at DESC LIMIT 5');$r['daily_collections']=$this->all("SELECT DATE(payment_date) collection_date,SUM(amount-refunded_amount) amount FROM payments WHERE deleted_at IS NULL AND status IN ('completed','partially_applied') AND payment_date>=CURDATE()-INTERVAL 6 DAY GROUP BY DATE(payment_date) ORDER BY collection_date");return$r;
 }
 public function exportRows(PaymentListFilters $f):array{$f=new PaymentListFilters(1,100,$f->status,$f->method,$f->accountId,$f->customerId,$f->invoiceId,$f->connectionId,$f->collectedBy,$f->dateFrom,$f->dateTo,$f->minAmount,$f->maxAmount,$f->search,$f->sort);$all=[];do{$r=$this->list($f);foreach($r['items'] as $p)$all[]=$p->toArray();$f=new PaymentListFilters($f->page+1,100,$f->status,$f->method,$f->accountId,$f->customerId,$f->invoiceId,$f->connectionId,$f->collectedBy,$f->dateFrom,$f->dateTo,$f->minAmount,$f->maxAmount,$f->search,$f->sort);}while($f->page<=$r['lastPage']);return$all;}
 private function select():string{return "p.*,c.full_name customer_name,c.customer_code,cn.connection_number,pm.code payment_method_code,pm.name payment_method_name,pa.name payment_account_name,u.name collected_by_name,r.receipt_number,r.pdf_status,(p.amount+p.discount_amount+p.adjustment_amount-p.applied_amount-p.refunded_amount) available_amount";}
 private function where(PaymentListFilters $f):array{$w=['p.deleted_at IS NULL'];$p=[];$joins='LEFT JOIN customers c ON c.id=p.customer_id LEFT JOIN connections cn ON cn.id=p.connection_id LEFT JOIN payment_methods pm ON pm.id=p.payment_method_id LEFT JOIN payment_accounts pa ON pa.id=p.payment_account_id LEFT JOIN users u ON u.id=p.collected_by LEFT JOIN receipts r ON r.payment_id=p.id AND r.deleted_at IS NULL';$map=['status'=>[$f->status,'p.status'],'method'=>[$f->method,'pm.code'],'account'=>[$f->accountId,'p.payment_account_id'],'customer'=>[$f->customerId,'p.customer_id'],'connection'=>[$f->connectionId,'p.connection_id'],'collector'=>[$f->collectedBy,'p.collected_by']];foreach($map as $k=>[$v,$c])if($v!==null){$w[]="$c=:$k";$p[$k]=$v;}if($f->invoiceId){$joins.=' JOIN payment_allocations paf ON paf.payment_id=p.id AND paf.reversed_at IS NULL';$w[]='paf.invoice_id=:invoice';$p['invoice']=$f->invoiceId;}if($f->dateFrom){$w[]='DATE(p.payment_date)>=:df';$p['df']=$f->dateFrom;}if($f->dateTo){$w[]='DATE(p.payment_date)<=:dt';$p['dt']=$f->dateTo;}if($f->minAmount){$w[]='p.amount>=:min';$p['min']=$f->minAmount;}if($f->maxAmount){$w[]='p.amount<=:max';$p['max']=$f->maxAmount;}if($f->search){$w[]='(p.payment_number LIKE :q OR r.receipt_number LIKE :q OR p.reference_number LIKE :q OR c.full_name LIKE :q OR c.customer_code LIKE :q OR cn.connection_number LIKE :q)';$p['q']='%'.$f->search.'%';}return[$w,$p,$joins];}
 private function all(string $sql,array $p=[]):array{$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetchAll();}
}
