<?php declare(strict_types=1);
use SkyFi\Shared\Http\{Request,Router};
use SkyFi\Shared\Http\Middleware\JwtAuthMiddleware;
use SkyFi\Shared\Http\Middleware\ProtectRoute;
use SkyFi\Shared\Providers\Container;
use SkyFi\System\Controllers\{BranchController,BrandingController,CompanySettingsController,DepartmentController,LocalizationController,NotificationSettingsController,SystemDashboardController,SystemSettingsController};
return static function (Router $router, Container $container): void {
    $auth=$container->get(JwtAuthMiddleware::class);
    $company=$container->get(CompanySettingsController::class); $branches=$container->get(BranchController::class); $departments=$container->get(DepartmentController::class); $settings=$container->get(SystemSettingsController::class); $branding=$container->get(BrandingController::class); $localization=$container->get(LocalizationController::class); $notifications=$container->get(NotificationSettingsController::class); $dashboard=$container->get(SystemDashboardController::class);
    $router->add('GET','/api/v1/system/dashboard',ProtectRoute::wrap($auth, $dashboard->dashboard(...))); $router->add('GET','/api/v1/system/configuration',ProtectRoute::wrap($auth, $dashboard->configuration(...)));
    $router->add('GET','/api/v1/system/company',ProtectRoute::wrap($auth, $company->show(...))); $router->add('PUT','/api/v1/system/company',ProtectRoute::wrap($auth, $company->update(...)));
    $router->add('GET','/api/v1/system/branches',ProtectRoute::wrap($auth, $branches->index(...))); $router->add('POST','/api/v1/system/branches',ProtectRoute::wrap($auth, $branches->store(...))); $router->add('GET','/api/v1/system/branches/{id}',ProtectRoute::wrap($auth, $branches->show(...))); $router->add('PUT','/api/v1/system/branches/{id}',ProtectRoute::wrap($auth, $branches->update(...))); $router->add('DELETE','/api/v1/system/branches/{id}',ProtectRoute::wrap($auth, $branches->destroy(...))); $router->add('POST','/api/v1/system/branches/{id}/activate',ProtectRoute::wrap($auth, $branches->activate(...))); $router->add('POST','/api/v1/system/branches/{id}/deactivate',ProtectRoute::wrap($auth, $branches->deactivate(...)));
    $router->add('GET','/api/v1/system/departments',ProtectRoute::wrap($auth, $departments->index(...))); $router->add('POST','/api/v1/system/departments',ProtectRoute::wrap($auth, $departments->store(...))); $router->add('GET','/api/v1/system/departments/{id}',ProtectRoute::wrap($auth, $departments->show(...))); $router->add('PUT','/api/v1/system/departments/{id}',ProtectRoute::wrap($auth, $departments->update(...))); $router->add('DELETE','/api/v1/system/departments/{id}',ProtectRoute::wrap($auth, $departments->destroy(...))); $router->add('POST','/api/v1/system/departments/{id}/activate',ProtectRoute::wrap($auth, $departments->activate(...))); $router->add('POST','/api/v1/system/departments/{id}/deactivate',ProtectRoute::wrap($auth, $departments->deactivate(...)));
    $router->add('GET','/api/v1/system/settings',ProtectRoute::wrap($auth, $settings->show(...))); $router->add('PUT','/api/v1/system/settings',ProtectRoute::wrap($auth, $settings->update(...))); $router->add('POST','/api/v1/system/settings/maintenance/enable',ProtectRoute::wrap($auth, $settings->enableMaintenance(...))); $router->add('POST','/api/v1/system/settings/maintenance/disable',ProtectRoute::wrap($auth, $settings->disableMaintenance(...)));
    $router->add('GET','/api/v1/system/branding',ProtectRoute::wrap($auth, $branding->show(...))); $router->add('PUT','/api/v1/system/branding',ProtectRoute::wrap($auth, $branding->update(...))); $router->add('POST','/api/v1/system/branding/assets',ProtectRoute::wrap($auth, $branding->upload(...)));
    $router->add('GET','/api/v1/system/localization',ProtectRoute::wrap($auth, $localization->show(...))); $router->add('PUT','/api/v1/system/localization',ProtectRoute::wrap($auth, $localization->update(...))); $router->add('GET','/api/v1/system/localization/options',ProtectRoute::wrap($auth, $localization->options(...)));
    $router->add('GET','/api/v1/system/notifications',ProtectRoute::wrap($auth, $notifications->show(...))); $router->add('PUT','/api/v1/system/notifications',ProtectRoute::wrap($auth, $notifications->update(...)));
};
