<?php declare(strict_types=1);
use SkyFi\Shared\Http\{Request,Router};
use SkyFi\Shared\Http\Middleware\JwtAuthMiddleware;
use SkyFi\Shared\Providers\Container;
use SkyFi\System\Controllers\{BranchController,BrandingController,CompanySettingsController,DepartmentController,LocalizationController,NotificationSettingsController,SystemDashboardController,SystemSettingsController};
return static function (Router $router, Container $container): void {
    $auth=$container->get(JwtAuthMiddleware::class);
    $protect=static fn(callable $handler): callable => static function(Request $request) use ($auth,$handler) { $a=$request->attributes(); $a['claims']=$auth->authenticate($request); return $handler($request->withAttributes($a)); };
    $company=$container->get(CompanySettingsController::class); $branches=$container->get(BranchController::class); $departments=$container->get(DepartmentController::class); $settings=$container->get(SystemSettingsController::class); $branding=$container->get(BrandingController::class); $localization=$container->get(LocalizationController::class); $notifications=$container->get(NotificationSettingsController::class); $dashboard=$container->get(SystemDashboardController::class);
    $router->add('GET','/api/v1/system/dashboard',$protect($dashboard->dashboard(...))); $router->add('GET','/api/v1/system/configuration',$protect($dashboard->configuration(...)));
    $router->add('GET','/api/v1/system/company',$protect($company->show(...))); $router->add('PUT','/api/v1/system/company',$protect($company->update(...)));
    $router->add('GET','/api/v1/system/branches',$protect($branches->index(...))); $router->add('POST','/api/v1/system/branches',$protect($branches->store(...))); $router->add('GET','/api/v1/system/branches/{id}',$protect($branches->show(...))); $router->add('PUT','/api/v1/system/branches/{id}',$protect($branches->update(...))); $router->add('DELETE','/api/v1/system/branches/{id}',$protect($branches->destroy(...))); $router->add('POST','/api/v1/system/branches/{id}/activate',$protect($branches->activate(...))); $router->add('POST','/api/v1/system/branches/{id}/deactivate',$protect($branches->deactivate(...)));
    $router->add('GET','/api/v1/system/departments',$protect($departments->index(...))); $router->add('POST','/api/v1/system/departments',$protect($departments->store(...))); $router->add('GET','/api/v1/system/departments/{id}',$protect($departments->show(...))); $router->add('PUT','/api/v1/system/departments/{id}',$protect($departments->update(...))); $router->add('DELETE','/api/v1/system/departments/{id}',$protect($departments->destroy(...))); $router->add('POST','/api/v1/system/departments/{id}/activate',$protect($departments->activate(...))); $router->add('POST','/api/v1/system/departments/{id}/deactivate',$protect($departments->deactivate(...)));
    $router->add('GET','/api/v1/system/settings',$protect($settings->show(...))); $router->add('PUT','/api/v1/system/settings',$protect($settings->update(...))); $router->add('POST','/api/v1/system/settings/maintenance/enable',$protect($settings->enableMaintenance(...))); $router->add('POST','/api/v1/system/settings/maintenance/disable',$protect($settings->disableMaintenance(...)));
    $router->add('GET','/api/v1/system/branding',$protect($branding->show(...))); $router->add('PUT','/api/v1/system/branding',$protect($branding->update(...))); $router->add('POST','/api/v1/system/branding/assets',$protect($branding->upload(...)));
    $router->add('GET','/api/v1/system/localization',$protect($localization->show(...))); $router->add('PUT','/api/v1/system/localization',$protect($localization->update(...))); $router->add('GET','/api/v1/system/localization/options',$protect($localization->options(...)));
    $router->add('GET','/api/v1/system/notifications',$protect($notifications->show(...))); $router->add('PUT','/api/v1/system/notifications',$protect($notifications->update(...)));
};
