export type SupplierStatus = 'active' | 'inactive' | 'on_hold' | 'archived';
export type ContractStatus = 'draft' | 'active' | 'expired' | 'terminated' | 'renewed';
export type QuotationStatus = 'draft' | 'received' | 'under_review' | 'accepted' | 'rejected' | 'expired';

export interface SupplierCategory { id: number; code: string; name: string; description: string | null; status: 'active' | 'inactive'; supplier_count?: number; }
export interface Supplier {
  id: number; supplier_code: string; company_name: string; tax_number: string | null; registration_number: string | null;
  address: string | null; city: string | null; country: string | null; contact_person: string | null; phone: string | null;
  email: string | null; website: string | null; payment_terms: string | null; currency: string; notes: string | null;
  status: SupplierStatus; overall_rating: number | null; procurement_value: number; category_names?: string | null;
  categories?: SupplierCategory[]; contact_count: number; active_contract_count?: number; contract_count?: number;
  quotation_count?: number; purchase_order_count?: number; created_at: string; updated_at: string; deleted_at: string | null;
}
export interface SupplierContact { id: number; vendor_id: number; supplier_name: string; supplier_code: string; name: string; department: string | null; job_title: string | null; phone: string | null; email: string | null; is_primary: boolean | number; is_emergency: boolean | number; notes: string | null; created_at: string; }
export interface SupplierContract { id: number; vendor_id: number; supplier_name: string; supplier_code: string; contract_number: string; start_date: string; end_date: string; renewal_date: string | null; contract_value: string | number; currency: string; status: ContractStatus; attachment_name: string | null; attachment_reference: string | null; notes: string | null; days_remaining: number; is_expiring: boolean | number; created_at: string; }
export interface QuotationItem { id?: number; product_id?: number | null; product_name?: string | null; sku?: string | null; description: string; quantity: number | string; unit_price: number | string; line_total?: number | string; lead_time_days?: number | null; }
export interface SupplierQuotation { id: number; vendor_id: number; supplier_name: string; supplier_code: string; quotation_number: string; rfq_reference: string | null; quotation_date: string; valid_until: string | null; currency: string; subtotal: string | number; tax_amount: string | number; total_amount: string | number; status: QuotationStatus; notes: string | null; item_count?: number; items?: QuotationItem[]; created_at: string; }
export interface SupplierPerformance { eligible_orders: number; completed_orders: number; measured_deliveries: number; on_time_orders: number; delivery_performance_pct: number; order_completion_pct: number; product_quality_score: number | null; return_rate_pct: number; average_lead_time_days: number; procurement_value: number; currency: string; overall_rating: number | null; }
export interface SupplierRating extends SupplierPerformance { id: number; vendor_id: number; review_period_start: string; review_period_end: string; product_quality_score: number; notes: string | null; rated_by_name?: string; }
export interface VendorDashboard { active_suppliers: number; expiring_contracts: number; average_supplier_rating: number; top_suppliers: Array<{ id: number; supplier_code: string; company_name: string; overall_rating: string | number; delivery_performance_pct: string | number; product_quality_score: string | number }>; procurement_spend_by_supplier: Array<{ id: number; company_name: string; currency: string; amount: string | number }>; suppliers_by_status: Array<{ status: string; total: number }>; expiring_contract_items: Array<{ id: number; contract_number: string; end_date: string; renewal_date: string | null; vendor_id: number; supplier_name: string; days_remaining: number }>; }
export interface PriceComparisonRow { quotation_id: number; quotation_number: string; rfq_reference: string; quotation_date: string; valid_until: string | null; currency: string; status: string; vendor_id: number; supplier_name: string; item_id: number; product_id: number | null; item_name: string; sku: string | null; description: string; quantity: string | number; unit_price: string | number; line_total: string | number; lead_time_days: number | null; best_unit_price: string | number; is_best_price: boolean; }
export interface PurchaseOrderReference { id: number; po_number: string; status: string; currency: string; total_amount: string; order_date: string; expected_delivery_date: string | null; delivery_date: string | null; warehouse_name: string | null; }
export interface ProductReference { id: number; sku: string; name: string; status: string; tracking_mode: string; vendor_sku: string | null; is_default: boolean | number; last_purchase_cost: string | null; lead_time_days: number | null; unit_symbol: string; }
export interface FinancialReferences { invoices: Array<{ id: number; invoice_number: string; status: string; currency: string; total_amount: string; invoice_date: string; due_date: string | null; po_number: string | null }>; summary_by_currency: Array<{ currency: string; invoice_count: number; invoiced_total: string; open_total: string }>; finance_postings: Array<{ id: number; source_type: string; source_id: number; status: string; idempotency_key: string; last_error: string | null; created_at: string; transaction_id: string | null; journal_description: string | null }>; }
export interface ListMeta { current_page: number; per_page: number; total: number; last_page: number; }
export interface Resource<T> { type: string; id: string; attributes: T; }
export interface PaginatedResponse<T> { data: Resource<T>[]; meta: ListMeta; }
export interface SupplierFormValues { supplier_code: string; company_name: string; tax_number?: string; registration_number?: string; address?: string; city?: string; country?: string; contact_person?: string; phone?: string; email?: string; website?: string; payment_terms?: string; currency: string; notes?: string; status: Exclude<SupplierStatus, 'archived'>; category_ids: number[]; }
export interface ContactFormValues { name: string; department?: string; job_title?: string; phone?: string; email?: string; is_primary: boolean; is_emergency: boolean; notes?: string; }
export interface ContractFormValues { contract_number: string; start_date: string; end_date: string; renewal_date?: string; contract_value: number; currency: string; status: ContractStatus; attachment_name?: string; attachment_reference?: string; notes?: string; }
export interface QuotationFormValues { quotation_number: string; rfq_reference?: string; quotation_date: string; valid_until?: string; currency: string; tax_amount: number; status: QuotationStatus; notes?: string; items: Array<{ product_id?: number | null; description: string; quantity: number; unit_price: number; lead_time_days?: number | null }>; }
export interface RatingFormValues { review_period_start: string; review_period_end: string; product_quality_score: number; currency: string; notes?: string; }
