-- Customer Management module schema
-- Apply through the project's migration runner; do not alter production manually.

CREATE TABLE customers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_code VARCHAR(50) NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    father_husband_name VARCHAR(200) NULL,
    cnic VARCHAR(50) NULL,
    phone VARCHAR(20) NOT NULL,
    whatsapp VARCHAR(20) NULL,
    email VARCHAR(255) NULL,
    address VARCHAR(500) NOT NULL,
    city VARCHAR(100) NOT NULL,
    area VARCHAR(100) NOT NULL,
    notes TEXT NULL,
    status ENUM('lead','prospect','active','suspended','disconnected','archived') NOT NULL DEFAULT 'lead',
    registration_date DATE NULL,
    installation_date DATE NULL,
    assigned_package_id BIGINT UNSIGNED NULL,
    connection_status ENUM('pending','installed','active','down') NULL,
    installation_technician_id BIGINT UNSIGNED NULL,
    emergency_contact_name VARCHAR(200) NULL,
    emergency_contact_phone VARCHAR(20) NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_customers_customer_code (customer_code),
    UNIQUE KEY uk_customers_cnic (cnic),
    KEY idx_customers_status (status),
    KEY idx_customers_city_area (city, area),
    KEY idx_customers_phone (phone),
    KEY idx_customers_created_at (created_at),
    KEY idx_customers_deleted_at (deleted_at),
    KEY idx_customers_full_name (full_name),
    CONSTRAINT fk_customers_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_customers_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_customers_technician FOREIGN KEY (installation_technician_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
