-- Network Devices module schema
-- Apply through the project's migration runner; do not alter production manually.

CREATE TABLE network_devices (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pop_site_id BIGINT UNSIGNED NULL,
    tower_id BIGINT UNSIGNED NULL,
    name VARCHAR(150) NOT NULL,
    device_type ENUM('router', 'switch', 'radio', 'access_point', 'olt', 'onu', 'ups', 'other') NOT NULL,
    vendor VARCHAR(100) NULL,
    model VARCHAR(150) NULL,
    serial_number VARCHAR(100) NULL,
    mac_address VARCHAR(17) NULL,
    ip_address VARCHAR(45) NULL,
    firmware_version VARCHAR(100) NULL,
    location_description VARCHAR(255) NULL,
    management_vlan SMALLINT UNSIGNED NULL,
    management_username VARCHAR(100) NULL,
    management_password_encrypted TEXT NULL,
    status ENUM('inventory', 'deployed', 'maintenance', 'offline', 'decommissioned') DEFAULT 'inventory',
    notes TEXT NULL,
    mikrotik_router_id BIGINT UNSIGNED NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_network_devices_serial (serial_number),
    KEY idx_network_devices_pop_site (pop_site_id),
    KEY idx_network_devices_tower (tower_id),
    KEY idx_network_devices_type (device_type),
    KEY idx_network_devices_status (status),
    KEY idx_network_devices_ip (ip_address),
    KEY idx_network_devices_mikrotik (mikrotik_router_id),
    KEY idx_network_devices_deleted_at (deleted_at),
    CONSTRAINT fk_network_devices_pop_site FOREIGN KEY (pop_site_id) REFERENCES pop_sites (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_network_devices_tower FOREIGN KEY (tower_id) REFERENCES towers (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_network_devices_mikrotik FOREIGN KEY (mikrotik_router_id) REFERENCES mikrotik_routers (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_network_devices_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_network_devices_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;