<?php

declare(strict_types=1);

namespace SkyFi\Database\Seeders;

final class PermissionCatalog
{
    /** @return array<string, string> Permission name to description. */
    public static function all(): array
    {
        return [
            '*' => 'Unrestricted access to all permissions.',
            'view:dashboard' => 'View a dashboard.',
            'view:dashboard:company' => 'View the company dashboard.',
            'view:dashboard:regional' => 'View a regional dashboard.',
            'view:report:financial' => 'View financial reports.',
            'view:report:subscriber' => 'View subscriber reports.',
            'view:report:network' => 'View network reports.',
            'view:report:regional' => 'View regional reports.',
            'view:report:inventory' => 'View inventory reports.',
            'view:audit-log' => 'View the audit log.',
            'customers.view' => 'View customer list and details.',
            'customers.create' => 'Create new customers.',
            'customers.update' => 'Update customer details.',
            'customers.delete' => 'Delete customers.',
            'customers.export' => 'Export customer data.',
            'customers.manage' => 'Manage customer status and assignments.',
            'packages.view' => 'View internet packages, statistics, and activity.',
            'packages.create' => 'Create and duplicate internet packages.',
            'packages.update' => 'Update internet package configuration.',
            'packages.delete' => 'Soft-delete internet packages.',
            'packages.export' => 'Export internet package data.',
            'packages.manage' => 'Manage package status and bulk catalog actions.',
            'billing.view' => 'View invoices, billing schedules, and billing history.',
            'billing.create' => 'Create manual invoices.',
            'billing.update' => 'Update draft and pending invoices.',
            'billing.delete' => 'Soft-delete invoice records.',
            'billing.generate' => 'Generate single and bulk invoices.',
            'billing.export' => 'Export invoice data.',
            'billing.manage' => 'Manage invoice status, billing schedules, and late fee rules.',
            'payments.view' => 'View payments, receipts, allocations, and statistics.',
            'payments.create' => 'Create and receive payments.',
            'payments.update' => 'Update eligible pending payments.',
            'payments.delete' => 'Soft-delete eligible payment records.',
            'payments.refund' => 'Issue full and partial payment refunds.',
            'payments.export' => 'Export payment data and receipts.',
            'payments.manage' => 'Allocate, reverse, and bulk-manage payments.',
            'view:customer' => 'View customer records.',
            'view:customer:basic' => 'View basic customer records within scope.',
            'view:customer:own' => 'View the signed-in customer record.',
            'view:customer:contact_and_address' => 'View scoped customer contact and address details.',
            'view:customer:network-details' => 'View customer network details.',
            'update:customer:contact' => 'Update customer contact details.',
            'update:customer:notes' => 'Update customer notes.',
            'update:customer:own' => 'Update the signed-in customer record.',
            'manage:invoice' => 'Manage invoices.',
            'view:invoice' => 'View invoices.',
            'view:invoice:own' => 'View the signed-in customer invoices.',
            'manage:payment' => 'Manage payments.',
            'view:payment' => 'View payments.',
            'view:payment:own' => 'View the signed-in customer payments.',
            'create:payment:manual' => 'Record a manual payment.',
            'create:payment:own' => 'Create a payment for the signed-in customer.',
            'manage:credit' => 'Manage customer credits.',
            'create:refund:small' => 'Create a small refund.',
            'create:refund:large' => 'Create a large refund requiring approval.',
            'execute:billing-run' => 'Execute a billing run.',
            'execute:dunning-process' => 'Execute the dunning process.',
            'manage:service-plan' => 'Manage service plans.',
            'view:service-plan' => 'View service plans.',
            'view:service' => 'View services.',
            'view:service:own' => 'View the signed-in customer service.',
            'execute:service-availability-check' => 'Check service availability.',
            'execute:service:reconnect' => 'Reconnect a customer service.',
            'manage:lead' => 'Manage sales leads.',
            'create:quote' => 'Create a quote.',
            'create:customer' => 'Create a customer.',
            'manage:ticket' => 'Manage support tickets.',
            'view:ticket' => 'View support tickets.',
            'view:ticket:own' => 'View the signed-in customer tickets.',
            'view:network-status:customer' => 'View customer network status.',
            'view:network-status:global' => 'View global network status.',
            'execute:site-survey' => 'Execute a site survey.',
            'execute:service:diagnostics' => 'Execute service diagnostics.',
            'view:work-order' => 'View work orders.',
            'view:work-order:own' => 'View assigned work orders.',
            'update:work-order:own' => 'Update assigned work orders.',
            'manage:tower' => 'Manage towers.',
            'manage:mikrotik-router' => 'Manage MikroTik routers.',
            'infrastructure.view' => 'View POP sites, towers, sectors, and network devices.',
            'infrastructure.create' => 'Create new infrastructure entities.',
            'infrastructure.update' => 'Update infrastructure entities.',
            'infrastructure.delete' => 'Soft delete infrastructure entities.',
            'infrastructure.manage' => 'Manage infrastructure status and advanced operations.',
            'mikrotik.view' => 'View MikroTik routers, discovery data, and health snapshots.',
            'mikrotik.create' => 'Register MikroTik routers, groups, and tags.',
            'mikrotik.update' => 'Update MikroTik router configuration, state, groups, and tags.',
            'mikrotik.delete' => 'Delete MikroTik routers, groups, and tags.',
            'mikrotik.connect' => 'Test MikroTik connections and run discovery or health checks.',
            'pppoe.view' => 'View PPPoE accounts, configurations, and profiles.',
            'pppoe.create' => 'Create PPPoE accounts and provision secrets on routers.',
            'pppoe.update' => 'Update PPPoE secrets, passwords, profiles, and packages.',
            'pppoe.delete' => 'Delete PPPoE accounts and remove secrets from routers.',
            'pppoe.enable' => 'Enable PPPoE accounts on routers.',
            'pppoe.disable' => 'Disable PPPoE accounts on routers and disconnect active sessions.',
            'pppoe.sync' => 'Perform PPPoE synchronization audits, discrepancy checks, repairs, and imports.',
            'pppoe.monitor' => 'Monitor live active PPPoE sessions and view session history.',
            'pppoe.manage' => 'Full management of PPPoE user state including suspend, resume, and force disconnect.',
            'view:ip-address-pool' => 'View IP address pools.',
            'execute:provisioning:manual' => 'Execute manual provisioning.',
            'execute:config-backup' => 'Execute a configuration backup.',
            'view:inventory:own-vehicle' => 'View inventory in the assigned vehicle.',
            'manage:inventory-item' => 'Manage inventory items.',
            'manage:warehouse' => 'Manage warehouses.',
            'execute:stock-transfer' => 'Execute a stock transfer.',
            'manage:vendor' => 'Manage vendors.',
            'manage:purchase-order' => 'Manage purchase orders.',
            'manage:user' => 'Manage users.',
            'manage:role' => 'Manage roles.',
            'manage:settings' => 'Manage system settings.',
            'update:user:role' => 'Update user roles within scope.',
            'manage:ticket:own' => 'Manage the signed-in customer tickets.',
        ];
    }
}
