<?php

declare(strict_types=1);

namespace SkyFi\Reports\QueryBuilders;

use SkyFi\Reports\Contracts\ReportQueryBuilderContract;
use SkyFi\Reports\DTOs\ReportRequest;

final class ReportQueryBuilder implements ReportQueryBuilderContract
{
    public function build(ReportRequest $request, bool $export = false): array
    {
        $definition = $this->definition($request->reportKey);
        $where = $definition['where'] ?? ['1=1'];
        $params = [];
        $filters = $definition['filters'] ?? [];
        foreach ($request->filters as $key => $value) {
            if ($value === '' || $value === null || !isset($filters[$key])) continue;
            $column = $filters[$key];
            if ($key === 'date_from') { $where[] = "{$column} >= :date_from"; $params['date_from'] = $value; }
            elseif ($key === 'date_to') { $where[] = "{$column} < DATE_ADD(:date_to, INTERVAL 1 DAY)"; $params['date_to'] = $value; }
            elseif ($key === 'region') { $where[] = "{$column} = :region"; $params['region'] = $value; }
            else { $where[] = "{$column} = :{$key}"; $params[$key] = (int)$value ?: $value; }
        }
        $sql = str_replace('{{where}}', implode(' AND ', $where), $definition['sql']);
        $countSql = 'SELECT COUNT(*) FROM (' . $sql . ') report_count';
        $allowed = array_column($definition['columns'], 'key');
        if ($request->sortBy !== null && in_array($request->sortBy, $allowed, true)) {
            $sql .= ' ORDER BY `' . $request->sortBy . '` ' . strtoupper($request->sortDirection);
        } elseif (isset($definition['order'])) $sql .= ' ORDER BY ' . $definition['order'];
        if (!$export) {
            $sql .= ' LIMIT :report_limit OFFSET :report_offset';
            $params['report_limit'] = $request->perPage;
            $params['report_offset'] = ($request->page - 1) * $request->perPage;
        }
        return ['sql'=>$sql,'count_sql'=>$countSql,'params'=>$params,'columns'=>$definition['columns']];
    }

    /** @return array<string, mixed> */
    private function definition(string $key): array
    {
        $c = fn(array $items): array => array_map(static fn(array $item): array => ['key'=>$item[0],'label'=>$item[1],'type'=>$item[2] ?? 'string'], $items);
        $commonCustomer = ['date_from'=>'c.created_at','date_to'=>'c.created_at','customer_id'=>'c.id','region'=>'c.city','package_id'=>'c.assigned_package_id','technician_id'=>'c.installation_technician_id','status'=>'c.status'];
        $definitions = [
            'customer.growth'=>['sql'=>"SELECT DATE_FORMAT(c.created_at,'%Y-%m') period, COUNT(*) new_customers FROM customers c WHERE {{where}} GROUP BY period",'where'=>['c.deleted_at IS NULL'],'filters'=>$commonCustomer,'columns'=>$c([['period','Period'],['new_customers','New customers','number']]),'order'=>'period ASC'],
            'customer.active'=>['sql'=>'SELECT c.customer_code,c.full_name,c.phone,c.city,c.area,c.registration_date,c.status FROM customers c WHERE {{where}}','where'=>["c.deleted_at IS NULL","c.status='active'"],'filters'=>$commonCustomer,'columns'=>$c([['customer_code','Customer code'],['full_name','Customer'],['phone','Phone'],['city','City'],['area','Area'],['registration_date','Registered','date'],['status','Status']])],
            'customer.suspended'=>['sql'=>'SELECT c.customer_code,c.full_name,c.phone,c.city,c.area,c.updated_at suspended_at,c.status FROM customers c WHERE {{where}}','where'=>["c.deleted_at IS NULL","c.status='suspended'"],'filters'=>$commonCustomer,'columns'=>$c([['customer_code','Customer code'],['full_name','Customer'],['phone','Phone'],['city','City'],['area','Area'],['suspended_at','Suspended at','date'],['status','Status']])],
            'customer.new-installations'=>['sql'=>"SELECT DATE_FORMAT(COALESCE(w.completed_at,c.installation_date),'%Y-%m') period,COUNT(*) installations,SUM(CASE WHEN w.status='completed' THEN 1 ELSE 0 END) completed FROM customers c LEFT JOIN work_orders w ON w.customer_id=c.id AND w.type='installation' AND w.deleted_at IS NULL WHERE {{where}} GROUP BY period",'where'=>['c.deleted_at IS NULL','COALESCE(w.completed_at,c.installation_date) IS NOT NULL'],'filters'=>array_merge($commonCustomer,['date_from'=>'COALESCE(w.completed_at,c.installation_date)','date_to'=>'COALESCE(w.completed_at,c.installation_date)','technician_id'=>'w.assigned_technician_id']),'columns'=>$c([['period','Period'],['installations','Installations','number'],['completed','Completed','number']]),'order'=>'period ASC'],
            'customer.churn'=>['sql'=>"SELECT DATE_FORMAT(c.updated_at,'%Y-%m') period,COUNT(*) churned_customers FROM customers c WHERE {{where}} GROUP BY period",'where'=>['c.deleted_at IS NULL',"c.status IN ('disconnected','archived')"],'filters'=>$commonCustomer,'columns'=>$c([['period','Period'],['churned_customers','Churned customers','number']]),'order'=>'period ASC'],
            'connection.active'=>['sql'=>'SELECT cn.connection_number,c.full_name customer,p.name package,cn.type,cn.activation_date,cn.pop_site,cn.tower,cn.status FROM connections cn JOIN customers c ON c.id=cn.customer_id JOIN packages p ON p.id=cn.package_id WHERE {{where}}','where'=>['cn.deleted_at IS NULL',"cn.status='active'"],'filters'=>['date_from'=>'cn.activation_date','date_to'=>'cn.activation_date','customer_id'=>'cn.customer_id','region'=>'c.city','pop_site_id'=>'cn.pop_site_id','tower_id'=>'cn.tower_id','package_id'=>'cn.package_id','technician_id'=>'cn.technician_id','status'=>'cn.status'],'columns'=>$c([['connection_number','Connection'],['customer','Customer'],['package','Package'],['type','Type'],['activation_date','Activated','date'],['pop_site','POP'],['tower','Tower'],['status','Status']])],
            'connection.types'=>['sql'=>'SELECT cn.type,COUNT(*) connections FROM connections cn JOIN customers c ON c.id=cn.customer_id WHERE {{where}} GROUP BY cn.type','where'=>['cn.deleted_at IS NULL'],'filters'=>['date_from'=>'cn.created_at','date_to'=>'cn.created_at','customer_id'=>'cn.customer_id','region'=>'c.city','pop_site_id'=>'cn.pop_site_id','tower_id'=>'cn.tower_id','package_id'=>'cn.package_id','technician_id'=>'cn.technician_id','status'=>'cn.status'],'columns'=>$c([['type','Connection type'],['connections','Connections','number']])],
            'connection.package-distribution'=>['sql'=>'SELECT p.name package,COUNT(*) connections FROM connections cn JOIN packages p ON p.id=cn.package_id JOIN customers c ON c.id=cn.customer_id WHERE {{where}} GROUP BY p.id,p.name','where'=>['cn.deleted_at IS NULL'],'filters'=>['date_from'=>'cn.created_at','date_to'=>'cn.created_at','customer_id'=>'cn.customer_id','region'=>'c.city','pop_site_id'=>'cn.pop_site_id','tower_id'=>'cn.tower_id','package_id'=>'cn.package_id','status'=>'cn.status'],'columns'=>$c([['package','Package'],['connections','Connections','number']]),'order'=>'connections DESC'],
            'billing.outstanding-invoices'=>['sql'=>'SELECT i.invoice_number,c.full_name customer,i.issue_date,i.due_date,i.currency,i.total_amount,i.balance_due,i.status FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE {{where}}','where'=>['i.deleted_at IS NULL','i.balance_due>0',"i.status NOT IN ('cancelled','void')"],'filters'=>['date_from'=>'i.issue_date','date_to'=>'i.issue_date','customer_id'=>'i.customer_id','region'=>'c.city','package_id'=>'i.package_id','status'=>'i.status'],'columns'=>$c([['invoice_number','Invoice'],['customer','Customer'],['issue_date','Issue date','date'],['due_date','Due date','date'],['currency','Currency'],['total_amount','Total','currency'],['balance_due','Balance','currency'],['status','Status']])],
            'billing.paid-invoices'=>['sql'=>'SELECT i.invoice_number,c.full_name customer,i.issue_date,i.due_date,i.currency,i.total_amount,i.status FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE {{where}}','where'=>['i.deleted_at IS NULL',"i.status='paid'"],'filters'=>['date_from'=>'i.issue_date','date_to'=>'i.issue_date','customer_id'=>'i.customer_id','region'=>'c.city','package_id'=>'i.package_id','status'=>'i.status'],'columns'=>$c([['invoice_number','Invoice'],['customer','Customer'],['issue_date','Issue date','date'],['due_date','Due date','date'],['currency','Currency'],['total_amount','Total','currency'],['status','Status']])],
            'billing.overdue-invoices'=>['sql'=>'SELECT i.invoice_number,c.full_name customer,i.due_date,DATEDIFF(CURRENT_DATE,i.due_date) days_overdue,i.currency,i.balance_due,i.status FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE {{where}}','where'=>['i.deleted_at IS NULL','i.balance_due>0','i.due_date<CURRENT_DATE',"i.status NOT IN ('paid','cancelled','void')"],'filters'=>['date_from'=>'i.due_date','date_to'=>'i.due_date','customer_id'=>'i.customer_id','region'=>'c.city','package_id'=>'i.package_id','status'=>'i.status'],'columns'=>$c([['invoice_number','Invoice'],['customer','Customer'],['due_date','Due date','date'],['days_overdue','Days overdue','number'],['currency','Currency'],['balance_due','Balance','currency'],['status','Status']]),'order'=>'days_overdue DESC'],
            'billing.revenue-by-month'=>['sql'=>"SELECT DATE_FORMAT(i.issue_date,'%Y-%m') period,i.currency,SUM(i.total_amount-i.balance_due) revenue FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE {{where}} GROUP BY period,i.currency",'where'=>['i.deleted_at IS NULL',"i.status NOT IN ('draft','cancelled','void')"],'filters'=>['date_from'=>'i.issue_date','date_to'=>'i.issue_date','customer_id'=>'i.customer_id','region'=>'c.city','package_id'=>'i.package_id','status'=>'i.status'],'columns'=>$c([['period','Period'],['currency','Currency'],['revenue','Revenue','currency']]),'order'=>'period ASC'],
            'payment.collections'=>['sql'=>'SELECT p.payment_number,c.full_name customer,p.payment_date,pm.name payment_method,p.reference_number,p.currency,p.amount,p.refunded_amount,(p.amount-p.refunded_amount) net_amount,p.status FROM payments p JOIN customers c ON c.id=p.customer_id JOIN payment_methods pm ON pm.id=p.payment_method_id WHERE {{where}}','where'=>['p.deleted_at IS NULL'],'filters'=>['date_from'=>'p.payment_date','date_to'=>'p.payment_date','customer_id'=>'p.customer_id','region'=>'c.city','status'=>'p.status'],'columns'=>$c([['payment_number','Payment'],['customer','Customer'],['payment_date','Date','date'],['payment_method','Method'],['reference_number','Reference'],['currency','Currency'],['amount','Gross','currency'],['refunded_amount','Refunded','currency'],['net_amount','Net','currency'],['status','Status']])],
            'payment.methods'=>['sql'=>'SELECT pm.name payment_method,p.currency,COUNT(*) transactions,SUM(p.amount-p.refunded_amount) collected FROM payments p JOIN payment_methods pm ON pm.id=p.payment_method_id JOIN customers c ON c.id=p.customer_id WHERE {{where}} GROUP BY pm.id,pm.name,p.currency','where'=>['p.deleted_at IS NULL',"p.status='completed'"],'filters'=>['date_from'=>'p.payment_date','date_to'=>'p.payment_date','customer_id'=>'p.customer_id','region'=>'c.city','status'=>'p.status'],'columns'=>$c([['payment_method','Method'],['currency','Currency'],['transactions','Transactions','number'],['collected','Collected','currency']])],
            'payment.daily-collections'=>['sql'=>"SELECT DATE(p.payment_date) period,p.currency,COUNT(*) transactions,SUM(p.amount-p.refunded_amount) collected FROM payments p JOIN customers c ON c.id=p.customer_id WHERE {{where}} GROUP BY period,p.currency",'where'=>['p.deleted_at IS NULL',"p.status='completed'"],'filters'=>['date_from'=>'p.payment_date','date_to'=>'p.payment_date','customer_id'=>'p.customer_id','region'=>'c.city','status'=>'p.status'],'columns'=>$c([['period','Day','date'],['currency','Currency'],['transactions','Transactions','number'],['collected','Collected','currency']]),'order'=>'period ASC'],
            'payment.monthly-collections'=>['sql'=>"SELECT DATE_FORMAT(p.payment_date,'%Y-%m') period,p.currency,COUNT(*) transactions,SUM(p.amount-p.refunded_amount) collected FROM payments p JOIN customers c ON c.id=p.customer_id WHERE {{where}} GROUP BY period,p.currency",'where'=>['p.deleted_at IS NULL',"p.status='completed'"],'filters'=>['date_from'=>'p.payment_date','date_to'=>'p.payment_date','customer_id'=>'p.customer_id','region'=>'c.city','status'=>'p.status'],'columns'=>$c([['period','Month'],['currency','Currency'],['transactions','Transactions','number'],['collected','Collected','currency']]),'order'=>'period ASC'],
            'finance.income-statement'=>['sql'=>"SELECT category,entry_type,'PKR' currency,SUM(amount) amount FROM (SELECT category,'revenue' entry_type,amount,transaction_date FROM revenue UNION ALL SELECT category,'expense',amount,transaction_date FROM expenses) statement_lines WHERE {{where}} GROUP BY category,entry_type",'where'=>['1=1'],'filters'=>['date_from'=>'transaction_date','date_to'=>'transaction_date'],'columns'=>$c([['category','Category'],['entry_type','Type'],['currency','Currency'],['amount','Amount','currency']])],
            'finance.expense-summary'=>['sql'=>'SELECT e.category,COUNT(*) transactions,SUM(e.amount) amount FROM expenses e WHERE {{where}} GROUP BY e.category','where'=>['1=1'],'filters'=>['date_from'=>'e.transaction_date','date_to'=>'e.transaction_date'],'columns'=>$c([['category','Expense category'],['transactions','Transactions','number'],['amount','Amount','currency']]),'order'=>'amount DESC'],
            'finance.cash-flow-summary'=>['sql'=>"SELECT DATE_FORMAT(transaction_date,'%Y-%m') period,SUM(inflow) inflow,SUM(outflow) outflow,SUM(inflow-outflow) net_cash_flow FROM (SELECT transaction_date,amount inflow,0 outflow FROM revenue UNION ALL SELECT transaction_date,0,amount FROM expenses) f WHERE {{where}} GROUP BY period",'where'=>['1=1'],'filters'=>['date_from'=>'transaction_date','date_to'=>'transaction_date'],'columns'=>$c([['period','Period'],['inflow','Inflow','currency'],['outflow','Outflow','currency'],['net_cash_flow','Net cash flow','currency']]),'order'=>'period ASC'],
            'finance.revenue-vs-expenses'=>['sql'=>"SELECT period,SUM(revenue) revenue,SUM(expenses) expenses FROM (SELECT DATE_FORMAT(transaction_date,'%Y-%m') period,amount revenue,0 expenses,transaction_date FROM revenue UNION ALL SELECT DATE_FORMAT(transaction_date,'%Y-%m'),0,amount,transaction_date FROM expenses) f WHERE {{where}} GROUP BY period",'where'=>['1=1'],'filters'=>['date_from'=>'transaction_date','date_to'=>'transaction_date'],'columns'=>$c([['period','Period'],['revenue','Revenue','currency'],['expenses','Expenses','currency']]),'order'=>'period ASC'],
            'inventory.stock-levels'=>['sql'=>'SELECT w.name warehouse,p.sku,p.name product,SUM(b.quantity) quantity_on_hand,SUM(CASE WHEN b.stock_condition=\'reserved\' THEN b.quantity ELSE 0 END) quantity_reserved,SUM(CASE WHEN b.stock_condition=\'available\' THEN b.quantity ELSE 0 END) available,p.reorder_level FROM inventory_stock_balances b JOIN inventory_products p ON p.id=b.product_id JOIN warehouse_locations wl ON wl.id=b.warehouse_location_id JOIN warehouses w ON w.id=wl.warehouse_id WHERE {{where}} GROUP BY w.id,w.name,p.id,p.sku,p.name,p.reorder_level','where'=>['p.deleted_at IS NULL','w.deleted_at IS NULL'],'filters'=>['warehouse_id'=>'wl.warehouse_id','status'=>'p.status'],'columns'=>$c([['warehouse','Warehouse'],['sku','SKU'],['product','Product'],['quantity_on_hand','On hand','number'],['quantity_reserved','Reserved','number'],['available','Available','number'],['reorder_level','Reorder level','number']]),'order'=>'w.name,p.name'],
            'inventory.low-stock'=>['sql'=>'SELECT w.name warehouse,p.sku,p.name product,SUM(b.quantity) quantity_on_hand,p.reorder_level,(p.reorder_level-SUM(b.quantity)) shortage FROM inventory_stock_balances b JOIN inventory_products p ON p.id=b.product_id JOIN warehouse_locations wl ON wl.id=b.warehouse_location_id JOIN warehouses w ON w.id=wl.warehouse_id WHERE {{where}} GROUP BY w.id,w.name,p.id,p.sku,p.name,p.reorder_level HAVING SUM(b.quantity)<=p.reorder_level','where'=>['p.deleted_at IS NULL','w.deleted_at IS NULL'],'filters'=>['warehouse_id'=>'wl.warehouse_id','status'=>'p.status'],'columns'=>$c([['warehouse','Warehouse'],['sku','SKU'],['product','Product'],['quantity_on_hand','On hand','number'],['reorder_level','Reorder level','number'],['shortage','Shortage','number']]),'order'=>'shortage DESC'],
            'inventory.asset-assignment'=>['sql'=>'SELECT a.asset_tag,p.name product,a.serial_number,aa.assignment_type,COALESCE(aa.customer_id,aa.tower_id,aa.pop_site_id,aa.technician_id,aa.warehouse_location_id) assignee_id,aa.assigned_at,aa.released_at,a.status FROM inventory_assets a JOIN inventory_products p ON p.id=a.product_id LEFT JOIN inventory_asset_assignments aa ON aa.asset_id=a.id AND aa.released_at IS NULL LEFT JOIN warehouse_locations awl ON awl.id=aa.warehouse_location_id WHERE {{where}}','where'=>['a.deleted_at IS NULL'],'filters'=>['date_from'=>'aa.assigned_at','date_to'=>'aa.assigned_at','warehouse_id'=>'awl.warehouse_id','status'=>'a.status'],'columns'=>$c([['asset_tag','Asset tag'],['product','Product'],['serial_number','Serial'],['assignment_type','Assigned to type'],['assignee_id','Assignee ID'],['assigned_at','Assigned at','date'],['released_at','Released at','date'],['status','Status']])],
            'inventory.asset-depreciation'=>['sql'=>"SELECT 'Not configured' status,'Asset depreciation requires an approved useful-life and depreciation policy.' note WHERE {{where}}",'where'=>['1=1'],'filters'=>[],'columns'=>$c([['status','Status'],['note','Note']])],
            'purchasing.purchase-orders'=>['sql'=>'SELECT po.po_number,v.company_name supplier,w.name warehouse,po.order_date,po.expected_delivery_date,po.currency,po.total_amount,po.status FROM purchase_orders po JOIN vendors v ON v.id=po.vendor_id LEFT JOIN warehouses w ON w.id=po.warehouse_id WHERE {{where}}','where'=>['po.deleted_at IS NULL'],'filters'=>['date_from'=>'po.order_date','date_to'=>'po.order_date','supplier_id'=>'po.vendor_id','warehouse_id'=>'po.warehouse_id','status'=>'po.status'],'columns'=>$c([['po_number','PO number'],['supplier','Supplier'],['warehouse','Warehouse'],['order_date','Order date','date'],['expected_delivery_date','Expected delivery','date'],['currency','Currency'],['total_amount','Amount','currency'],['status','Status']])],
            'purchasing.goods-receipts'=>['sql'=>'SELECT gr.receipt_number,po.po_number,v.company_name supplier,w.name warehouse,gr.received_at,gr.status FROM goods_receipts gr JOIN purchase_orders po ON po.id=gr.purchase_order_id JOIN vendors v ON v.id=po.vendor_id LEFT JOIN warehouses w ON w.id=gr.warehouse_id WHERE {{where}}','where'=>['gr.deleted_at IS NULL'],'filters'=>['date_from'=>'gr.received_at','date_to'=>'gr.received_at','supplier_id'=>'po.vendor_id','warehouse_id'=>'gr.warehouse_id','status'=>'gr.status'],'columns'=>$c([['receipt_number','Receipt'],['po_number','PO'],['supplier','Supplier'],['warehouse','Warehouse'],['received_at','Received at','date'],['status','Status']])],
            'purchasing.procurement-spend'=>['sql'=>'SELECT v.company_name supplier,po.currency,COUNT(*) orders,SUM(po.total_amount) spend FROM purchase_orders po JOIN vendors v ON v.id=po.vendor_id WHERE {{where}} GROUP BY v.id,v.company_name,po.currency','where'=>['po.deleted_at IS NULL',"po.status NOT IN ('draft','cancelled')"],'filters'=>['date_from'=>'po.order_date','date_to'=>'po.order_date','supplier_id'=>'po.vendor_id','warehouse_id'=>'po.warehouse_id','status'=>'po.status'],'columns'=>$c([['supplier','Supplier'],['currency','Currency'],['orders','Orders','number'],['spend','Spend','currency']]),'order'=>'spend DESC'],
            'vendor.supplier-performance'=>['sql'=>'SELECT v.company_name supplier,sr.review_period_start,sr.review_period_end,sr.delivery_performance_pct,sr.order_completion_pct,sr.product_quality_score,sr.return_rate_pct,sr.average_lead_time_days,sr.overall_rating FROM supplier_ratings sr JOIN vendors v ON v.id=sr.vendor_id WHERE {{where}}','where'=>['sr.deleted_at IS NULL','v.deleted_at IS NULL'],'filters'=>['date_from'=>'sr.review_period_start','date_to'=>'sr.review_period_end','supplier_id'=>'sr.vendor_id','status'=>'v.status'],'columns'=>$c([['supplier','Supplier'],['review_period_start','From','date'],['review_period_end','To','date'],['delivery_performance_pct','On time %','number'],['order_completion_pct','Completion %','number'],['product_quality_score','Quality','number'],['return_rate_pct','Return %','number'],['average_lead_time_days','Lead time days','number'],['overall_rating','Rating','number']])],
            'vendor.supplier-spend'=>['sql'=>'SELECT v.company_name supplier,po.currency,COUNT(*) orders,SUM(po.total_amount) spend FROM vendors v JOIN purchase_orders po ON po.vendor_id=v.id WHERE {{where}} GROUP BY v.id,v.company_name,po.currency','where'=>['v.deleted_at IS NULL','po.deleted_at IS NULL',"po.status NOT IN ('draft','cancelled')"],'filters'=>['date_from'=>'po.order_date','date_to'=>'po.order_date','supplier_id'=>'v.id','status'=>'v.status'],'columns'=>$c([['supplier','Supplier'],['currency','Currency'],['orders','Orders','number'],['spend','Spend','currency']]),'order'=>'spend DESC'],
            'support.ticket-volume'=>['sql'=>"SELECT DATE_FORMAT(t.created_at,'%Y-%m') period,t.status,COUNT(*) tickets FROM support_tickets t JOIN customers c ON c.id=t.customer_id LEFT JOIN ticket_assignments ta ON ta.ticket_id=t.id AND ta.ended_at IS NULL WHERE {{where}} GROUP BY period,t.status",'where'=>['t.deleted_at IS NULL'],'filters'=>['date_from'=>'t.created_at','date_to'=>'t.created_at','customer_id'=>'t.customer_id','region'=>'c.city','technician_id'=>'ta.staff_user_id','status'=>'t.status'],'columns'=>$c([['period','Period'],['status','Status'],['tickets','Tickets','number']]),'order'=>'period ASC'],
            'support.sla-compliance'=>['sql'=>"SELECT CASE WHEN t.response_breached_at IS NOT NULL OR t.resolution_breached_at IS NOT NULL THEN 'Breached' ELSE 'Compliant' END sla_status,COUNT(*) tickets,ROUND(COUNT(*)*100/(SELECT COUNT(*) FROM support_tickets WHERE deleted_at IS NULL),2) percentage FROM support_tickets t JOIN customers c ON c.id=t.customer_id LEFT JOIN ticket_assignments ta ON ta.ticket_id=t.id AND ta.ended_at IS NULL WHERE {{where}} GROUP BY sla_status",'where'=>['t.deleted_at IS NULL'],'filters'=>['date_from'=>'t.created_at','date_to'=>'t.created_at','customer_id'=>'t.customer_id','region'=>'c.city','technician_id'=>'ta.staff_user_id','status'=>'t.status'],'columns'=>$c([['sla_status','SLA status'],['tickets','Tickets','number'],['percentage','Percentage','number']])],
            'support.resolution-time'=>['sql'=>"SELECT DATE_FORMAT(t.resolved_at,'%Y-%m') period,COUNT(*) resolved_tickets,ROUND(AVG(TIMESTAMPDIFF(MINUTE,t.created_at,t.resolved_at))/60,2) average_hours FROM support_tickets t JOIN customers c ON c.id=t.customer_id LEFT JOIN ticket_assignments ta ON ta.ticket_id=t.id AND ta.ended_at IS NULL WHERE {{where}} GROUP BY period",'where'=>['t.deleted_at IS NULL','t.resolved_at IS NOT NULL'],'filters'=>['date_from'=>'t.resolved_at','date_to'=>'t.resolved_at','customer_id'=>'t.customer_id','region'=>'c.city','technician_id'=>'ta.staff_user_id','status'=>'t.status'],'columns'=>$c([['period','Period'],['resolved_tickets','Resolved','number'],['average_hours','Average hours','number']]),'order'=>'period ASC'],
            'network.router-health'=>['sql'=>'SELECT r.name router,r.host,r.last_connection_status status,h.cpu_usage_percent,ROUND((1-h.memory_free_bytes/NULLIF(h.memory_total_bytes,0))*100,2) memory_usage_percent,h.uptime,h.checked_at recorded_at FROM mikrotik_routers r LEFT JOIN mikrotik_router_health_snapshots h ON h.router_id=r.id AND h.id=(SELECT MAX(h2.id) FROM mikrotik_router_health_snapshots h2 WHERE h2.router_id=r.id) WHERE {{where}}','where'=>['r.deleted_at IS NULL'],'filters'=>['date_from'=>'h.checked_at','date_to'=>'h.checked_at','status'=>'r.last_connection_status'],'columns'=>$c([['router','Router'],['host','Host'],['status','Status'],['cpu_usage_percent','CPU %','number'],['memory_usage_percent','Memory %','number'],['uptime','Uptime'],['recorded_at','Observed','date']])],
            'network.infrastructure-capacity'=>['sql'=>'SELECT ps.name pop_site,t.name tower,COUNT(DISTINCT s.id) sectors,COUNT(DISTINCT nd.id) devices,COUNT(DISTINCT cn.id) active_connections FROM pop_sites ps LEFT JOIN towers t ON t.pop_site_id=ps.id AND t.deleted_at IS NULL LEFT JOIN sectors s ON s.tower_id=t.id AND s.deleted_at IS NULL LEFT JOIN network_devices nd ON nd.pop_site_id=ps.id AND nd.deleted_at IS NULL LEFT JOIN connections cn ON cn.pop_site_id=ps.id AND cn.status=\'active\' AND cn.deleted_at IS NULL WHERE {{where}} GROUP BY ps.id,ps.name,t.id,t.name','where'=>['ps.deleted_at IS NULL'],'filters'=>['pop_site_id'=>'ps.id','tower_id'=>'t.id','status'=>'ps.status'],'columns'=>$c([['pop_site','POP site'],['tower','Tower'],['sectors','Sectors','number'],['devices','Devices','number'],['active_connections','Active connections','number']])],
            'network.pppoe-sessions'=>['sql'=>"SELECT DATE_FORMAT(s.started_at,'%Y-%m-%d') period,COUNT(*) sessions,SUM(s.bytes_in) bytes_in,SUM(s.bytes_out) bytes_out,AVG(s.uptime_seconds) average_uptime_seconds FROM pppoe_session_history s JOIN pppoe_accounts a ON a.id=s.account_id WHERE {{where}} GROUP BY period",'where'=>['1=1'],'filters'=>['date_from'=>'s.started_at','date_to'=>'s.started_at','customer_id'=>'a.customer_id','status'=>'a.status'],'columns'=>$c([['period','Day'],['sessions','Sessions','number'],['bytes_in','Bytes in','number'],['bytes_out','Bytes out','number'],['average_uptime_seconds','Avg uptime','number']]),'order'=>'period ASC'],
            'network.hotspot-sessions'=>['sql'=>"SELECT DATE_FORMAT(s.started_at,'%Y-%m-%d') period,COUNT(*) sessions,SUM(s.bytes_in) bytes_in,SUM(s.bytes_out) bytes_out,AVG(s.uptime_seconds) average_uptime_seconds FROM hotspot_session_history s JOIN hotspot_users u ON u.id=s.hotspot_user_id WHERE {{where}} GROUP BY period",'where'=>['1=1'],'filters'=>['date_from'=>'s.started_at','date_to'=>'s.started_at','customer_id'=>'u.customer_id','status'=>'u.status'],'columns'=>$c([['period','Day'],['sessions','Sessions','number'],['bytes_in','Bytes in','number'],['bytes_out','Bytes out','number'],['average_uptime_seconds','Avg uptime','number']]),'order'=>'period ASC'],
            'network.bandwidth-usage'=>['sql'=>"SELECT DATE_FORMAT(s.checked_at,'%Y-%m-%d %H:00') period,SUM(s.rx_bps) rx_bps,SUM(s.tx_bps) tx_bps,SUM(s.rx_bytes) rx_bytes,SUM(s.tx_bytes) tx_bytes FROM monitoring_interface_snapshots s WHERE {{where}} GROUP BY period",'where'=>['1=1'],'filters'=>['date_from'=>'s.checked_at','date_to'=>'s.checked_at'],'columns'=>$c([['period','Period'],['rx_bps','Download bps','number'],['tx_bps','Upload bps','number'],['rx_bytes','Downloaded bytes','number'],['tx_bytes','Uploaded bytes','number']]),'order'=>'period ASC'],
            'field.installation-success-rate'=>['sql'=>"SELECT DATE_FORMAT(w.created_at,'%Y-%m') period,COUNT(*) installations,SUM(w.status='completed') successful,SUM(w.status='failed') failed,ROUND(SUM(w.status='completed')*100/NULLIF(SUM(w.status IN ('completed','failed')),0),2) success_rate FROM work_orders w JOIN customers c ON c.id=w.customer_id WHERE {{where}} GROUP BY period",'where'=>['w.deleted_at IS NULL',"w.type='installation'"],'filters'=>['date_from'=>'w.created_at','date_to'=>'w.created_at','customer_id'=>'w.customer_id','region'=>'c.city','pop_site_id'=>'w.pop_site_id','tower_id'=>'w.tower_id','technician_id'=>'w.assigned_technician_id','status'=>'w.status'],'columns'=>$c([['period','Period'],['installations','Installations','number'],['successful','Successful','number'],['failed','Failed','number'],['success_rate','Success %','number']]),'order'=>'period ASC'],
            'field.technician-productivity'=>['sql'=>"SELECT u.name technician,t.employee_code,COUNT(w.id) assigned_jobs,SUM(w.status='completed') completed_jobs,ROUND(AVG(CASE WHEN w.completed_at IS NOT NULL THEN TIMESTAMPDIFF(MINUTE,w.started_at,w.completed_at)/60 END),2) average_hours FROM technicians t JOIN users u ON u.id=t.user_id LEFT JOIN work_orders w ON w.assigned_technician_id=t.id AND w.deleted_at IS NULL WHERE {{where}} GROUP BY t.id,u.name,t.employee_code",'where'=>['t.deleted_at IS NULL'],'filters'=>['date_from'=>'w.created_at','date_to'=>'w.created_at','technician_id'=>'t.id','status'=>'w.status'],'columns'=>$c([['technician','Technician'],['employee_code','Employee code'],['assigned_jobs','Assigned','number'],['completed_jobs','Completed','number'],['average_hours','Average hours','number']]),'order'=>'completed_jobs DESC'],
            'field.average-completion-time'=>['sql'=>"SELECT DATE_FORMAT(w.completed_at,'%Y-%m') period,w.type,COUNT(*) completed_jobs,ROUND(AVG(TIMESTAMPDIFF(MINUTE,w.started_at,w.completed_at))/60,2) average_hours FROM work_orders w JOIN customers c ON c.id=w.customer_id WHERE {{where}} GROUP BY period,w.type",'where'=>['w.deleted_at IS NULL','w.started_at IS NOT NULL','w.completed_at IS NOT NULL'], 'filters'=>['date_from'=>'w.completed_at','date_to'=>'w.completed_at','customer_id'=>'w.customer_id','region'=>'c.city','pop_site_id'=>'w.pop_site_id','tower_id'=>'w.tower_id','technician_id'=>'w.assigned_technician_id','status'=>'w.status'],'columns'=>$c([['period','Period'],['type','Work type'],['completed_jobs','Completed','number'],['average_hours','Average hours','number']]),'order'=>'period ASC'],
        ];
        return $definitions[$key];
    }
}
