<?php

declare(strict_types=1);
namespace SkyFi\Payments\Services;
use SkyFi\Payments\Contracts\{PaymentRepositoryContract,PaymentServiceContract};
use SkyFi\Payments\DTOs\{PaymentData,PaymentListFilters};use SkyFi\Payments\Models\Payment;
use SkyFi\Payments\Validators\PaymentValidator;use SkyFi\Rbac\Contracts\AuditLoggerContract;
use SkyFi\Shared\Exceptions\{NotFoundException,ValidationException};
final class PaymentService implements PaymentServiceContract
{
 public function __construct(private readonly PaymentRepositoryContract $repo,private readonly PaymentValidator $validator,private readonly AuditLoggerContract $audit){}
 public function list(PaymentListFilters $f):array{return$this->repo->list($f);}public function get(int $id):Payment{return$this->repo->find($id)??throw new NotFoundException('Payment not found.');}
 public function create(PaymentData $d,int $u,?string $ip,?string $ua):Payment{return$this->persist($d,$u,$ip,$ua,false);}
 public function receive(PaymentData $d,int $u,?string $ip,?string $ua):Payment{return$this->persist($d,$u,$ip,$ua,true);}
 private function persist(PaymentData $d,int $u,?string $ip,?string $ua,bool $receive):Payment
 {
  return $this->repo->transaction(function()use($d,$u,$ip,$ua,$receive){$this->validateRelations($d);$number=$this->number('PAY');$payment=$this->repo->create(['payment_number'=>$number,'customer_id'=>$d->customerId,'connection_id'=>$d->connectionId,'payment_method_id'=>$d->methodId,'payment_account_id'=>$d->accountId,'amount'=>$d->amount,'tax_amount'=>$d->tax,'discount_amount'=>$d->discount,'adjustment_amount'=>$d->adjustment,'currency'=>'PKR','payment_date'=>date('Y-m-d H:i:s',strtotime($d->paymentDate)),'reference_number'=>$d->reference,'collected_by'=>$u,'status'=>$receive?'completed':'pending','notes'=>$d->notes,'created_by'=>$u]);$this->repo->addActivity($payment->id(),$receive?'received':'created',$receive?'Payment received.':'Pending payment created.',$u);
   if($receive&&$d->allocations!==[])$payment=$this->applyAllocations($payment,$d->allocations,$u);
   if($receive){$receipt=$this->number('RCP');$snapshot=$payment->toArray();$snapshot['receipt_number']=$receipt;$this->repo->addReceipt($payment->id(),$receipt,$u,$snapshot);$this->repo->addActivity($payment->id(),'receipt_issued',"Receipt $receipt issued.",$u);$this->repo->addFinancialEvent($payment->id(),null,'payment.completed',$payment->amount(),$snapshot,'payment.completed.'.$payment->id());}
   $result=$this->get($payment->id());foreach($d->attachments as $attachment){/* metadata upload is intentionally reserved */}$this->audit->log($u,$receive?'receive':'create','payment',$payment->id(),null,$result->toArray(),$ip,$ua);return$result;});
 }
 public function update(int $id,PaymentData $d,int $u,?string $ip,?string $ua):Payment
 {
  $p=$this->get($id);if($p->status()!=='pending')throw$this->error('status','Only pending payments can be updated.');$this->validateRelations($d,$id);$old=$p->toArray();$updated=$this->repo->update($id,['customer_id'=>$d->customerId,'connection_id'=>$d->connectionId,'payment_method_id'=>$d->methodId,'payment_account_id'=>$d->accountId,'amount'=>$d->amount,'tax_amount'=>$d->tax,'discount_amount'=>$d->discount,'adjustment_amount'=>$d->adjustment,'payment_date'=>date('Y-m-d H:i:s',strtotime($d->paymentDate)),'reference_number'=>$d->reference,'notes'=>$d->notes,'updated_by'=>$u]);$this->repo->addActivity($id,'updated','Pending payment updated.',$u);$this->audit->log($u,'update','payment',$id,$old,$updated->toArray(),$ip,$ua);return$this->get($id);
 }
 public function delete(int $id,int $u,?string $ip,?string $ua):void{$p=$this->get($id);if(!in_array($p->status(),['pending','failed','cancelled'],true))throw$this->error('status','Completed payments cannot be deleted; reverse them instead.');$this->repo->softDelete($id);$this->audit->log($u,'delete','payment',$id,$p->toArray(),null,$ip,$ua);}
 public function allocate(int $id,array $a,int $u,?string $ip,?string $ua):Payment{return$this->repo->transaction(function()use($id,$a,$u,$ip,$ua){$p=$this->repo->find($id,true)??throw new NotFoundException('Payment not found.');if(!in_array($p->status(),['completed','partially_applied'],true))throw$this->error('status','Only completed payments can be allocated.');$old=$p->toArray();$result=$this->applyAllocations($p,$a,$u);$this->audit->log($u,'allocate','payment',$id,$old,$result->toArray(),$ip,$ua);return$result;});}
 private function applyAllocations(Payment $p,array $allocations,int $u):Payment
 {
  $current=$p->toArray();$available=(float)$current['amount']+(float)$current['discount_amount']+(float)$current['adjustment_amount']-(float)$current['applied_amount']-(float)$current['refunded_amount'];$sum=0.0;$invoiceIds=[];
  foreach($allocations as $i=>$a){if(!is_array($a))throw$this->error("allocations.$i",'Invalid allocation.');$amount=(float)$this->validator->positiveAmount($a['amount']??0,"allocations.$i.amount");$type=(string)($a['allocation_type']??'invoice');if(!in_array($type,['invoice','advance_balance','credit_balance'],true))throw$this->error("allocations.$i.allocation_type",'Invalid allocation type.');$invoiceId=isset($a['invoice_id'])?(int)$a['invoice_id']:null;if($type==='invoice'){$invoice=$invoiceId?$this->repo->invoiceForAllocation($invoiceId,$p->customerId()):null;if(!$invoice||in_array($invoice['status'],['draft','cancelled','void'],true))throw$this->error("allocations.$i.invoice_id",'Select an eligible invoice for this customer.');if($amount>(float)$invoice['balance_due']+0.0001)throw$this->error("allocations.$i.amount",'Allocation exceeds the invoice balance.');$invoiceIds[]=$invoiceId;}else{$invoiceId=null;}$sum+=$amount;if($sum>$available+0.0001)throw$this->error('allocations','Allocations exceed the available payment balance.');$allocationId=$this->repo->addAllocation($p->id(),['invoice_id'=>$invoiceId,'allocation_type'=>$type,'amount'=>number_format($amount,2,'.',''),'allocated_at'=>date('Y-m-d H:i:s'),'allocated_by'=>$u,'notes'=>isset($a['notes'])?(string)$a['notes']:null]);if($type!=='invoice')$this->repo->addCredit($p->customerId(),$p->id(),$allocationId,$type==='advance_balance'?'advance':'credit',number_format($amount,2,'.',''),$u,ucwords(str_replace('_',' ',$type)).' created from payment.');}
  $applied=(float)$current['applied_amount']+$sum;$settlement=(float)$current['amount']+(float)$current['discount_amount']+(float)$current['adjustment_amount'];$status=$applied+0.0001<$settlement?'partially_applied':'completed';$this->repo->update($p->id(),['applied_amount'=>number_format($applied,2,'.',''),'status'=>$status,'updated_by'=>$u]);foreach(array_unique($invoiceIds) as $invoiceId)$this->repo->recalculateInvoice($invoiceId,$u,"Payment {$current['payment_number']} allocated.");$this->repo->addActivity($p->id(),'allocated','Payment allocation recorded.',$u,['amount'=>number_format($sum,2,'.','')]);return$this->get($p->id());
 }
 public function reverse(int $id,string $reason,int $u,?string $ip,?string $ua):Payment
 {
  if(trim($reason)==='')throw$this->error('reason','A reversal reason is required.');return$this->repo->transaction(function()use($id,$reason,$u,$ip,$ua){$p=$this->repo->find($id,true)??throw new NotFoundException('Payment not found.');if(!in_array($p->status(),['completed','partially_applied'],true))throw$this->error('status','This payment cannot be reversed.');$old=$p->toArray();$rows=$this->repo->reverseAllocations($id,$u);$this->repo->update($id,['status'=>'cancelled','applied_amount'=>'0.00','updated_by'=>$u]);foreach($rows as $r)if($r['invoice_id'])$this->repo->recalculateInvoice((int)$r['invoice_id'],$u,"Payment {$old['payment_number']} reversed.");$this->repo->addActivity($id,'reversed',$reason,$u);$this->repo->addFinancialEvent($id,null,'payment.reversed',$p->amount(),['reason'=>$reason,'payment_number'=>$old['payment_number']],'payment.reversed.'.$id);$result=$this->get($id);$this->audit->log($u,'reverse','payment',$id,$old,$result->toArray(),$ip,$ua);return$result;});
 }
 public function refund(int $id,array $d,int $u,?string $ip,?string $ua):Payment
 {
  $amount=$this->validator->positiveAmount($d['amount']??0);$reason=trim((string)($d['reason']??''));if($reason==='')throw$this->error('reason','A refund reason is required.');return$this->repo->transaction(function()use($id,$d,$u,$ip,$ua,$amount,$reason){$p=$this->repo->find($id,true)??throw new NotFoundException('Payment not found.');if(!in_array($p->status(),['completed','partially_applied'],true))throw$this->error('status','This payment is not refundable.');$old=$p->toArray();$available=(float)$old['amount']-(float)$old['refunded_amount'];if((float)$amount>$available+0.0001)throw$this->error('amount','Refund exceeds the refundable payment amount.');$number=$this->number('REF');$rid=$this->repo->addRefund($id,$number,$amount,$reason,isset($d['notes'])?(string)$d['notes']:null,isset($d['reference_number'])?(string)$d['reference_number']:null,$u);$affected=$this->repo->refundAllocations($id,$amount,$u);$refunded=(float)$old['refunded_amount']+(float)$amount;$status=$refunded+0.0001>=(float)$old['amount']?'refunded':$p->status();$applied=max(0,(float)$old['applied_amount']-(float)$amount);$this->repo->update($id,['refunded_amount'=>number_format($refunded,2,'.',''),'applied_amount'=>number_format($applied,2,'.',''),'status'=>$status,'updated_by'=>$u]);foreach($affected as $invoiceId)$this->repo->recalculateInvoice($invoiceId,$u,"Refund $number applied to payment {$old['payment_number']}.");$this->repo->addActivity($id,'refunded',"Refund $number: $reason",$u,['amount'=>$amount]);$this->repo->addFinancialEvent($id,$rid,'payment.refunded',$amount,['refund_number'=>$number,'reason'=>$reason],'payment.refunded.'.$rid);$result=$this->get($id);$this->audit->log($u,'refund','payment',$id,$old,$result->toArray(),$ip,$ua);return$result;});
 }
 public function bulk(array $items,int $u,?string $ip,?string $ua):array{$results=[];foreach($items as $i=>$item){try{$clean=$this->validator->validate(is_array($item)?$item:[],true);$p=$this->receive(PaymentData::fromArray($item,$clean),$u,$ip,$ua);$results[]=['index'=>$i,'success'=>true,'payment'=>$p->toArray()];}catch(\Throwable $e){$results[]=['index'=>$i,'success'=>false,'error'=>$e->getMessage()];}}return['processed'=>count($items),'succeeded'=>count(array_filter($results,fn($r)=>$r['success'])),'failed'=>count(array_filter($results,fn($r)=>!$r['success'])),'results'=>$results];}
 public function lookups():array{return$this->repo->lookups();}public function statistics():array{return$this->repo->statistics();}public function export(PaymentListFilters $f):array{return$this->repo->exportRows($f);}
 private function validateRelations(PaymentData $d,?int $exclude=null):void{if(!$this->repo->customerExists($d->customerId))throw$this->error('customer_id','Customer not found.');if($d->connectionId&&!$this->repo->connectionBelongsTo($d->connectionId,$d->customerId))throw$this->error('connection_id','Connection does not belong to this customer.');$lookup=$this->repo->methodAndAccount($d->methodId,$d->accountId);if(!$lookup||!$lookup['is_active']||$lookup['is_future'])throw$this->error('payment_method_id','Payment method or account is unavailable.');if($lookup['requires_reference']&&!$d->reference)throw$this->error('reference_number','A reference number is required for this payment method.');if($d->reference&&$this->repo->referenceExists($d->reference,$exclude))throw$this->error('reference_number','This reference number has already been recorded.');}
 private function number(string $prefix):string{for($i=0;$i<20;$i++){$n=$prefix.'-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));if(!$this->repo->numberExists($n))return$n;}throw new \RuntimeException('Could not generate a unique transaction number.');}
 private function error(string $path,string $detail):ValidationException{return new ValidationException([['code'=>'invalid','detail'=>$detail,'source'=>['pointer'=>'/data/attributes/'.str_replace('.','/',$path)]]]);}
}
