<?php
declare(strict_types=1);
use SkyFi\FieldService\Controllers\{FieldOperationController,FieldServiceController,TechnicianController};
use SkyFi\Shared\Http\{Request,Router};
use SkyFi\Shared\Http\Middleware\JwtAuthMiddleware;
use SkyFi\Shared\Http\Middleware\ProtectRoute;
use SkyFi\Shared\Providers\Container;
return static function(Router $router,Container $container):void{
 $field=$container->get(FieldServiceController::class);$tech=$container->get(TechnicianController::class);$ops=$container->get(FieldOperationController::class);$auth=$container->get(JwtAuthMiddleware::class);
 $with=static fn(string$key,string$value,callable$h):callable=>static function(Request$r)use($key,$value,$h){$a=$r->attributes();$a['route_params']=[...($a['route_params']??[]),$key=>$value];return$h($r->withAttributes($a));};
 $router->add('GET','/api/v1/field-service/dashboard',ProtectRoute::wrap($auth, $field->dashboard(...)));
 $router->add('GET','/api/v1/field-service/schedule',ProtectRoute::wrap($auth, $field->schedule(...)));$router->add('GET','/api/v1/field-service/schedule/unscheduled',ProtectRoute::wrap($auth, $field->unscheduled(...)));
 $router->add('GET','/api/v1/field-service/lookups/{resource}',ProtectRoute::wrap($auth, $tech->lookup(...)));
 $router->add('GET','/api/v1/field-service/installation-requests',ProtectRoute::wrap($auth, $field->requests(...)));$router->add('POST','/api/v1/field-service/installation-requests',ProtectRoute::wrap($auth, $field->createRequest(...)));$router->add('GET','/api/v1/field-service/installation-requests/{id}',ProtectRoute::wrap($auth, $field->request(...)));$router->add('PUT','/api/v1/field-service/installation-requests/{id}',ProtectRoute::wrap($auth, $field->updateRequest(...)));$router->add('DELETE','/api/v1/field-service/installation-requests/{id}',ProtectRoute::wrap($auth, $field->deleteRequest(...)));foreach(['assign','schedule','reschedule','cancel','complete','create-work-order']as$a)$router->add('POST',"/api/v1/field-service/installation-requests/{id}/{$a}",ProtectRoute::wrap($auth, $with('action',$a,$field->requestAction(...))));
 $router->add('GET','/api/v1/field-service/work-orders',ProtectRoute::wrap($auth, $field->orders(...)));$router->add('POST','/api/v1/field-service/work-orders',ProtectRoute::wrap($auth, $field->createOrder(...)));$router->add('GET','/api/v1/field-service/work-orders/{id}',ProtectRoute::wrap($auth, $field->order(...)));$router->add('PUT','/api/v1/field-service/work-orders/{id}',ProtectRoute::wrap($auth, $field->updateOrder(...)));$router->add('DELETE','/api/v1/field-service/work-orders/{id}',ProtectRoute::wrap($auth, $field->deleteOrder(...)));$router->add('GET','/api/v1/field-service/work-orders/{id}/timeline',ProtectRoute::wrap($auth, $field->timeline(...)));foreach(['assign','schedule','reschedule','cancel','complete','status']as$a)$router->add($a==='status'?'PATCH':'POST',"/api/v1/field-service/work-orders/{id}/{$a}",ProtectRoute::wrap($auth, $with('action',$a,$field->orderAction(...))));
 foreach(['materials','visits','logs']as$res){$router->add('GET',"/api/v1/field-service/work-orders/{id}/{$res}",ProtectRoute::wrap($auth, $with('resource',$res,$ops->index(...))));$router->add('POST',"/api/v1/field-service/work-orders/{id}/{$res}",ProtectRoute::wrap($auth, $with('resource',$res,$ops->store(...))));if($res!=='visits'){$router->add('PUT',"/api/v1/field-service/work-orders/{id}/{$res}/{itemId}",ProtectRoute::wrap($auth, $with('resource',$res,$ops->update(...))));$router->add('DELETE',"/api/v1/field-service/work-orders/{id}/{$res}/{itemId}",ProtectRoute::wrap($auth, $with('resource',$res,$ops->destroy(...))));}}
 foreach(['check-in','check-out']as$a)$router->add('POST',"/api/v1/field-service/work-orders/{id}/visits/{itemId}/{$a}",ProtectRoute::wrap($auth, $with('action',$a,$ops->visitAction(...))));
 $router->add('GET','/api/v1/field-service/technicians',ProtectRoute::wrap($auth, $tech->index(...)));$router->add('POST','/api/v1/field-service/technicians',ProtectRoute::wrap($auth, $tech->store(...)));$router->add('GET','/api/v1/field-service/technicians/{id}',ProtectRoute::wrap($auth, $tech->show(...)));$router->add('PUT','/api/v1/field-service/technicians/{id}',ProtectRoute::wrap($auth, $tech->update(...)));$router->add('DELETE','/api/v1/field-service/technicians/{id}',ProtectRoute::wrap($auth, $tech->destroy(...)));$router->add('GET','/api/v1/field-service/technicians/{id}/schedule',ProtectRoute::wrap($auth, $tech->schedule(...)));foreach(['skills','service-areas','availability']as$res){$router->add('GET',"/api/v1/field-service/technicians/{id}/{$res}",ProtectRoute::wrap($auth, $with('resource',$res,$tech->relation(...))));$router->add('POST',"/api/v1/field-service/technicians/{id}/{$res}",ProtectRoute::wrap($auth, $with('resource',$res,$tech->addRelation(...))));$router->add('PUT',"/api/v1/field-service/technicians/{id}/{$res}/{relationId}",ProtectRoute::wrap($auth, $with('resource',$res,$tech->updateRelation(...))));$router->add('DELETE',"/api/v1/field-service/technicians/{id}/{$res}/{relationId}",ProtectRoute::wrap($auth, $with('resource',$res,$tech->deleteRelation(...))));}
};
