<?php
declare(strict_types=1);
use SkyFi\FieldService\Controllers\{FieldOperationController,FieldServiceController,TechnicianController};
use SkyFi\Shared\Http\{Request,Router};
use SkyFi\Shared\Http\Middleware\JwtAuthMiddleware;
use SkyFi\Shared\Providers\Container;
return static function(Router $router,Container $container):void{
 $field=$container->get(FieldServiceController::class);$tech=$container->get(TechnicianController::class);$ops=$container->get(FieldOperationController::class);$auth=$container->get(JwtAuthMiddleware::class);
 $protect=static fn(callable$h):callable=>static function(Request$r)use($auth,$h){$a=$r->attributes();$a['claims']=$auth->authenticate($r);return$h($r->withAttributes($a));};
 $with=static fn(string$key,string$value,callable$h):callable=>static function(Request$r)use($key,$value,$h){$a=$r->attributes();$a['route_params']=[...($a['route_params']??[]),$key=>$value];return$h($r->withAttributes($a));};
 $router->add('GET','/api/v1/field-service/dashboard',$protect($field->dashboard(...)));
 $router->add('GET','/api/v1/field-service/schedule',$protect($field->schedule(...)));$router->add('GET','/api/v1/field-service/schedule/unscheduled',$protect($field->unscheduled(...)));
 $router->add('GET','/api/v1/field-service/lookups/{resource}',$protect($tech->lookup(...)));
 $router->add('GET','/api/v1/field-service/installation-requests',$protect($field->requests(...)));$router->add('POST','/api/v1/field-service/installation-requests',$protect($field->createRequest(...)));$router->add('GET','/api/v1/field-service/installation-requests/{id}',$protect($field->request(...)));$router->add('PUT','/api/v1/field-service/installation-requests/{id}',$protect($field->updateRequest(...)));$router->add('DELETE','/api/v1/field-service/installation-requests/{id}',$protect($field->deleteRequest(...)));foreach(['assign','schedule','reschedule','cancel','complete','create-work-order']as$a)$router->add('POST',"/api/v1/field-service/installation-requests/{id}/{$a}",$protect($with('action',$a,$field->requestAction(...))));
 $router->add('GET','/api/v1/field-service/work-orders',$protect($field->orders(...)));$router->add('POST','/api/v1/field-service/work-orders',$protect($field->createOrder(...)));$router->add('GET','/api/v1/field-service/work-orders/{id}',$protect($field->order(...)));$router->add('PUT','/api/v1/field-service/work-orders/{id}',$protect($field->updateOrder(...)));$router->add('DELETE','/api/v1/field-service/work-orders/{id}',$protect($field->deleteOrder(...)));$router->add('GET','/api/v1/field-service/work-orders/{id}/timeline',$protect($field->timeline(...)));foreach(['assign','schedule','reschedule','cancel','complete','status']as$a)$router->add($a==='status'?'PATCH':'POST',"/api/v1/field-service/work-orders/{id}/{$a}",$protect($with('action',$a,$field->orderAction(...))));
 foreach(['materials','visits','logs']as$res){$router->add('GET',"/api/v1/field-service/work-orders/{id}/{$res}",$protect($with('resource',$res,$ops->index(...))));$router->add('POST',"/api/v1/field-service/work-orders/{id}/{$res}",$protect($with('resource',$res,$ops->store(...))));if($res!=='visits'){$router->add('PUT',"/api/v1/field-service/work-orders/{id}/{$res}/{itemId}",$protect($with('resource',$res,$ops->update(...))));$router->add('DELETE',"/api/v1/field-service/work-orders/{id}/{$res}/{itemId}",$protect($with('resource',$res,$ops->destroy(...))));}}
 foreach(['check-in','check-out']as$a)$router->add('POST',"/api/v1/field-service/work-orders/{id}/visits/{itemId}/{$a}",$protect($with('action',$a,$ops->visitAction(...))));
 $router->add('GET','/api/v1/field-service/technicians',$protect($tech->index(...)));$router->add('POST','/api/v1/field-service/technicians',$protect($tech->store(...)));$router->add('GET','/api/v1/field-service/technicians/{id}',$protect($tech->show(...)));$router->add('PUT','/api/v1/field-service/technicians/{id}',$protect($tech->update(...)));$router->add('DELETE','/api/v1/field-service/technicians/{id}',$protect($tech->destroy(...)));$router->add('GET','/api/v1/field-service/technicians/{id}/schedule',$protect($tech->schedule(...)));foreach(['skills','service-areas','availability']as$res){$router->add('GET',"/api/v1/field-service/technicians/{id}/{$res}",$protect($with('resource',$res,$tech->relation(...))));$router->add('POST',"/api/v1/field-service/technicians/{id}/{$res}",$protect($with('resource',$res,$tech->addRelation(...))));$router->add('PUT',"/api/v1/field-service/technicians/{id}/{$res}/{relationId}",$protect($with('resource',$res,$tech->updateRelation(...))));$router->add('DELETE',"/api/v1/field-service/technicians/{id}/{$res}/{relationId}",$protect($with('resource',$res,$tech->deleteRelation(...))));}
};
